//-----------------------------------------------------------------------------
//                 Copyright(c) 2016-2019 Innogrit Corporation
//                             All Rights reserved.
//
// The confidential and proprietary information contained in this file may
// only be used by a person authorized under and to the extent permitted
// by a subsisting licensing agreement from Innogrit Corporation.
// Dissemination of this information or reproduction of this material
// is strictly forbidden unless prior written permission is obtained
// from Innogrit Corporation.
//-----------------------------------------------------------------------------

#pragma once

/*
 * search request queue 0 nrm/high/urg
 * search request queue 1 nrm/high/urg
 *
 * unmap
 *
 * search pda result queue 0 nrm/high/urg
 * search pda result queue 1 nrm/high/urg
 *
 */

#if CPU_ID == 1
	#define L2P_GRP0_INT_MASK	BTN_FTL_NCL_INT_GRP0_MASK0
	#define L2P_GRP1_INT_MASK	BTN_FTL_NCL_INT_GRP1_MASK0
	#define L2P_GRP0_INT_STS	BTN_FTL_NCL_INT_GRP0_STS0
	#define L2P_GRP1_INT_STS	BTN_FTL_NCL_INT_GRP1_STS0
#elif CPU_ID == 2
	#define L2P_GRP0_INT_MASK	BTN_FTL_NCL_INT_GRP0_MASK1
	#define L2P_GRP1_INT_MASK	BTN_FTL_NCL_INT_GRP1_MASK1
	#define L2P_GRP0_INT_STS	BTN_FTL_NCL_INT_GRP0_STS1
	#define L2P_GRP1_INT_STS	BTN_FTL_NCL_INT_GRP1_STS1
#elif CPU_ID == 3
	#define L2P_GRP0_INT_MASK	BTN_FTL_NCL_INT_GRP0_MASK2
	#define L2P_GRP1_INT_MASK	BTN_FTL_NCL_INT_GRP1_MASK2
	#define L2P_GRP0_INT_STS	BTN_FTL_NCL_INT_GRP0_STS2
	#define L2P_GRP1_INT_STS	BTN_FTL_NCL_INT_GRP1_STS2
#elif CPU_ID == 4
	#define L2P_GRP0_INT_MASK	BTN_FTL_NCL_INT_GRP0_MASK3
	#define L2P_GRP1_INT_MASK	BTN_FTL_NCL_INT_GRP1_MASK3
	#define L2P_GRP0_INT_STS	BTN_FTL_NCL_INT_GRP0_STS3
	#define L2P_GRP1_INT_STS	BTN_FTL_NCL_INT_GRP1_STS3
#endif

enum {
	BACKUP_L2P_REG0 = BTN_FTL_NCL_CTRL0,
	BACKUP_L2P_REG1 = BTN_FTL_NCL_CTRL1,
	BACKUP_L2P_REG2 = BTN_FTL_NCL_CTRL2,
	BACKUP_L2P_REG3 = BTN_FTL_REGION0_DATA_TP_BASE_ADDR,
	BACKUP_L2P_REG4 = BTN_FTL_REGION0_DATA_DVBM_BASE_ADDR,
	BACKUP_L2P_REG5 = BTN_RSVD_PDA_RANGE,

	BACKUP_L2P_REG6 = BTN_UNMAPPED_PDA0,
	BACKUP_L2P_REG7 = BTN_PDA_CONF_REG0,
	BACKUP_L2P_REG8 = BTN_PDA_CONF_REG1,
	BACKUP_L2P_REG9 = BTN_CPDA_CONF_REG0,
	BACKUP_L2P_REG10 = BTN_PDA_RSLT_GRP_SEL_CONF_REG,
	BACKUP_L2P_REG11 = BTN_SPB_DIE_GRP_CONF_REG,
	BACKUP_L2P_REG12 = BTN_LDA_MASK,
	BACKUP_L2P_REG13 = BTN_RSVD_LDA_VALUE,
	BACKUP_L2P_REG14 = BTN_LDA_MAX_VALUE,
	BACKUP_L2P_REG15 = BTN_PDA_MASK,
	BACKUP_L2P_REG16 = BTN_UNMAPPED_PDA1,
	BACKUP_L2P_REG17 = BTN_UNMAPPED_PDA2,
	BACKUP_L2P_REG18 = BTN_UNMAPPED_PDA3,
	BACKUP_L2P_REG19 = BTN_L2P_TABLE_START_LDA,
	BACKUP_L2P_REG20 = BTN_L2P_TABLE_ENTRY_NUM,
	BACKUP_L2P_REG21 = BTN_FTL_STATUS_CNT_TABLE_CONFIG_REG0,
	BACKUP_L2P_REG22 = BTN_FTL_STATUS_CNT_TABLE_CONFIG_REG2,
	BACKUP_L2P_REG23 = BTN_FTL_STATUS_CNT_TABLE_CONFIG_REG3,
	BACKUP_L2P_REG24 = BTN_FTL_STATUS_CNT_NOTIF_THRESHOLD,
	BACKUP_L2P_REG25 = BTN_FTL_LTMODE_CONFIG,
	BACKUP_L2P_REG_CNT = 26
};

enum {
	L2P_PDA_MODE = 0,
	L2P_CPDA_MODE = 1,
};

#define L2P_INT_BUF_SZ	32768			///< l2p internal buffer size for valid count table

enum {
	TBL_IN_SRAM = 0,
	TBL_IN_DDR = 1,
	INV_TBL_LOC = 2
};

#define L2P_ERROR_CPU_ID	1	/// force l2p error detected on CPU1
#if defined(RDISK)

#ifndef CPU_BE_LITE
#define CPU_BE_LITE	5
#endif

#define SRCH_QUE0_NRM_CPU_ID	CPU_FE
#define SRCH_QUE0_HIGH_CPU_ID	5
#define SRCH_QUE0_URG_CPU_ID	5

// not ready
#define SRCH_QUE1_NRM_CPU_ID	5
#define SRCH_QUE1_HIGH_CPU_ID	5
#define SRCH_QUE1_URG_CPU_ID	5

#define UNMAP_QUE_CPU_ID	CPU_FE

#define SRCH_PDA_GRP0_CPU_ID	CPU_BE
#ifdef DUAL_BE
#define SRCH_PDA_GRP1_CPU_ID	CPU_BE_LITE
#else
#define SRCH_PDA_GRP1_CPU_ID	CPU_BE
#endif

#define UPDT_REQ_QUE0_CPU_ID	5
#define UPDT_REQ_QUE1_CPU_ID	CPU_FTL
#define UPDT_REQ_QUE2_CPU_ID	CPU_FTL
#define UPDT_REQ_QUE3_CPU_ID	5

#define UPDT_CMPL_QUE0_CPU_ID	5
#define UPDT_CMPL_QUE1_CPU_ID	CPU_FTL
#define UPDT_CMPL_QUE2_CPU_ID	CPU_BE
#define UPDT_CMPL_QUE3_CPU_ID	5

#define CMMT_CMPL_QUE0_CPU_ID	5
#define CMMT_CMPL_QUE1_CPU_ID	5
#define CMMT_CMPL_QUE2_CPU_ID	5
#define CMMT_CMPL_QUE3_CPU_ID	5

#define RECYCLE_QUE_CPU_ID	CPU_FTL

#define DVL_INFO_UPDT_REQ_QUE_CPU_ID	CPU_BE
#define DVL_INFO_UPDT_CPL_QUE_CPU_ID	CPU_BE

#define PDA_GEN_QUE0_CPU_ID	CPU_BE
#define PDA_GEN_QUE1_CPU_ID	5
#define PDA_GEN_QUE2_CPU_ID	5
#define PDA_GEN_QUE3_CPU_ID	5
#define PDA_GEN_QUE4_CPU_ID	5
#define PDA_GEN_QUE5_CPU_ID	5
#define PDA_GEN_QUE6_CPU_ID	5
#define PDA_GEN_QUE7_CPU_ID	5

#define PDA_GEN_LOC0_CPU_ID	CPU_BE
#define PDA_GEN_LOC1_CPU_ID	CPU_BE_LITE

#define PDA_GEN_RSP0_QUE0_CPU_ID	PDA_GEN_LOC0_CPU_ID
#define PDA_GEN_RSP1_QUE0_CPU_ID	PDA_GEN_LOC1_CPU_ID
#define PDA_GEN_RSP0_QUE1_CPU_ID	5 // not ready
#define PDA_GEN_RSP1_QUE1_CPU_ID	5 // not ready
#define PDA_GEN_RSP0_QUE2_CPU_ID	5
#define PDA_GEN_RSP1_QUE2_CPU_ID	5
#define PDA_GEN_RSP0_QUE3_CPU_ID	5
#define PDA_GEN_RSP1_QUE3_CPU_ID	5
#define PDA_GEN_RSP0_QUE4_CPU_ID	5
#define PDA_GEN_RSP1_QUE4_CPU_ID	5
#define PDA_GEN_RSP0_QUE5_CPU_ID	5
#define PDA_GEN_RSP1_QUE5_CPU_ID	5
#define PDA_GEN_RSP0_QUE6_CPU_ID	5
#define PDA_GEN_RSP1_QUE6_CPU_ID	5
#define PDA_GEN_RSP0_QUE7_CPU_ID	5
#define PDA_GEN_RSP1_QUE7_CPU_ID	5

#define STATUS_SRCH_REQ_QUE_CPU_ID	5
#define STATUS_SRCH_RSP_QUE_CPU_ID	5
#define STATUS_FET_REQ_QUE_CPU_ID	CPU_BE
#define STATUS_FET_RSP_QUE_CPU_ID	CPU_FTL
#define STATUS_CNT_NOTIFY_QUE_CPU_ID	CPU_FTL

#elif defined(RAWDISK)

#define SRCH_QUE0_NRM_CPU_ID	CPU_FE
#define SRCH_QUE0_HIGH_CPU_ID	5
#define SRCH_QUE0_URG_CPU_ID	5

// not ready
#define SRCH_QUE1_NRM_CPU_ID	5
#define SRCH_QUE1_HIGH_CPU_ID	5
#define SRCH_QUE1_URG_CPU_ID	5

#define UNMAP_QUE_CPU_ID	CPU_FE

#define SRCH_PDA_GRP0_CPU_ID	CPU_BE
#define SRCH_PDA_GRP1_CPU_ID	CPU_BE

#define UPDT_REQ_QUE0_CPU_ID	CPU_FE
#define UPDT_REQ_QUE1_CPU_ID	5
#define UPDT_REQ_QUE2_CPU_ID	5
#define UPDT_REQ_QUE3_CPU_ID	5

#define UPDT_CMPL_QUE0_CPU_ID	CPU_FE
#define UPDT_CMPL_QUE1_CPU_ID	5
#define UPDT_CMPL_QUE2_CPU_ID	5
#define UPDT_CMPL_QUE3_CPU_ID	5

#define CMMT_CMPL_QUE0_CPU_ID	CPU_BE
#define CMMT_CMPL_QUE1_CPU_ID	5
#define CMMT_CMPL_QUE2_CPU_ID	5
#define CMMT_CMPL_QUE3_CPU_ID	5

#define RECYCLE_QUE_CPU_ID	5

#define DVL_INFO_UPDT_REQ_QUE_CPU_ID	1
#define DVL_INFO_UPDT_CPL_QUE_CPU_ID	1

#define PDA_GEN_QUE0_CPU_ID	5
#define PDA_GEN_QUE1_CPU_ID	5
#define PDA_GEN_QUE2_CPU_ID	5
#define PDA_GEN_QUE3_CPU_ID	5
#define PDA_GEN_QUE4_CPU_ID	5
#define PDA_GEN_QUE5_CPU_ID	5
#define PDA_GEN_QUE6_CPU_ID	5
#define PDA_GEN_QUE7_CPU_ID	5

#define PDA_GEN_LOC0_CPU_ID	CPU_BE
#define PDA_GEN_LOC1_CPU_ID	CPU_BE

#define PDA_GEN_RSP0_QUE0_CPU_ID	PDA_GEN_LOC0_CPU_ID
#define PDA_GEN_RSP1_QUE0_CPU_ID	PDA_GEN_LOC1_CPU_ID
#define PDA_GEN_RSP0_QUE1_CPU_ID	5 // not ready
#define PDA_GEN_RSP1_QUE1_CPU_ID	5 // not ready
#define PDA_GEN_RSP0_QUE2_CPU_ID	5
#define PDA_GEN_RSP1_QUE2_CPU_ID	5
#define PDA_GEN_RSP0_QUE3_CPU_ID	5
#define PDA_GEN_RSP1_QUE3_CPU_ID	5
#define PDA_GEN_RSP0_QUE4_CPU_ID	5
#define PDA_GEN_RSP1_QUE4_CPU_ID	5
#define PDA_GEN_RSP0_QUE5_CPU_ID	5
#define PDA_GEN_RSP1_QUE5_CPU_ID	5
#define PDA_GEN_RSP0_QUE6_CPU_ID	5
#define PDA_GEN_RSP1_QUE6_CPU_ID	5
#define PDA_GEN_RSP0_QUE7_CPU_ID	5
#define PDA_GEN_RSP1_QUE7_CPU_ID	5

#define STATUS_SRCH_REQ_QUE_CPU_ID	CPU_FTL
#define STATUS_SRCH_RSP_QUE_CPU_ID     	CPU_FTL
#define STATUS_FET_REQ_QUE_CPU_ID	CPU_FTL
#define STATUS_FET_RSP_QUE_CPU_ID	CPU_FTL

#define STATUS_CNT_NOTIFY_QUE_CPU_ID	5

#elif defined(TFW_CTRL_L2P)

#define SRCH_QUE0_NRM_CPU_ID	1
#define SRCH_QUE0_HIGH_CPU_ID	1
#define SRCH_QUE0_URG_CPU_ID	1

// not ready
#define SRCH_QUE1_NRM_CPU_ID	5
#define SRCH_QUE1_HIGH_CPU_ID	5
#define SRCH_QUE1_URG_CPU_ID	5

#define UNMAP_QUE_CPU_ID	1

#define SRCH_PDA_GRP0_CPU_ID	1
#define SRCH_PDA_GRP1_CPU_ID	1

#define UPDT_REQ_QUE0_CPU_ID	1
#define UPDT_REQ_QUE1_CPU_ID	1
#define UPDT_REQ_QUE2_CPU_ID	5
#define UPDT_REQ_QUE3_CPU_ID	5

#define UPDT_CMPL_QUE0_CPU_ID	1
#define UPDT_CMPL_QUE1_CPU_ID	1
#define UPDT_CMPL_QUE2_CPU_ID	5
#define UPDT_CMPL_QUE3_CPU_ID	5

#define CMMT_CMPL_QUE0_CPU_ID	1
#define CMMT_CMPL_QUE1_CPU_ID	1
#define CMMT_CMPL_QUE2_CPU_ID	5
#define CMMT_CMPL_QUE3_CPU_ID	5

#define RECYCLE_QUE_CPU_ID	1

#define DVL_INFO_UPDT_REQ_QUE_CPU_ID	1
#define DVL_INFO_UPDT_CPL_QUE_CPU_ID	1

#define PDA_GEN_QUE0_CPU_ID	1
#define PDA_GEN_QUE1_CPU_ID	1
#define PDA_GEN_QUE2_CPU_ID	4
#define PDA_GEN_QUE3_CPU_ID	4
#define PDA_GEN_QUE4_CPU_ID	4
#define PDA_GEN_QUE5_CPU_ID	4
#define PDA_GEN_QUE6_CPU_ID	4
#define PDA_GEN_QUE7_CPU_ID	4

#define PDA_GEN_LOC0_CPU_ID	1
#define PDA_GEN_LOC1_CPU_ID	1

#define PDA_GEN_RSP0_QUE0_CPU_ID	PDA_GEN_LOC0_CPU_ID
#define PDA_GEN_RSP1_QUE0_CPU_ID	PDA_GEN_LOC1_CPU_ID
#define PDA_GEN_RSP0_QUE1_CPU_ID	PDA_GEN_LOC0_CPU_ID
#define PDA_GEN_RSP1_QUE1_CPU_ID	PDA_GEN_LOC1_CPU_ID
#define PDA_GEN_RSP0_QUE2_CPU_ID	4
#define PDA_GEN_RSP1_QUE2_CPU_ID	4
#define PDA_GEN_RSP0_QUE3_CPU_ID	4
#define PDA_GEN_RSP1_QUE3_CPU_ID	4
#define PDA_GEN_RSP0_QUE4_CPU_ID	4
#define PDA_GEN_RSP1_QUE4_CPU_ID	4
#define PDA_GEN_RSP0_QUE5_CPU_ID	4
#define PDA_GEN_RSP1_QUE5_CPU_ID	4
#define PDA_GEN_RSP0_QUE6_CPU_ID	4
#define PDA_GEN_RSP1_QUE6_CPU_ID	4
#define PDA_GEN_RSP0_QUE7_CPU_ID	4
#define PDA_GEN_RSP1_QUE7_CPU_ID	4

#define STATUS_SRCH_REQ_QUE_CPU_ID	1
#define STATUS_SRCH_RSP_QUE_CPU_ID     	1
#define STATUS_FET_REQ_QUE_CPU_ID	1
#define STATUS_FET_RSP_QUE_CPU_ID	1

#define STATUS_CNT_NOTIFY_QUE_CPU_ID	1

#else

#define SRCH_QUE0_NRM_CPU_ID	5
#define SRCH_QUE0_HIGH_CPU_ID	5
#define SRCH_QUE0_URG_CPU_ID	5

// not ready
#define SRCH_QUE1_NRM_CPU_ID	5
#define SRCH_QUE1_HIGH_CPU_ID	5
#define SRCH_QUE1_URG_CPU_ID	5

#define UNMAP_QUE_CPU_ID	5

#define SRCH_PDA_GRP0_CPU_ID	5
#define SRCH_PDA_GRP1_CPU_ID	5

#define UPDT_REQ_QUE0_CPU_ID	5
#define UPDT_REQ_QUE1_CPU_ID	5
#define UPDT_REQ_QUE2_CPU_ID	5
#define UPDT_REQ_QUE3_CPU_ID	5

#define UPDT_CMPL_QUE0_CPU_ID	5
#define UPDT_CMPL_QUE1_CPU_ID	5
#define UPDT_CMPL_QUE2_CPU_ID	5
#define UPDT_CMPL_QUE3_CPU_ID	5

#define CMMT_CMPL_QUE0_CPU_ID	5
#define CMMT_CMPL_QUE1_CPU_ID	5
#define CMMT_CMPL_QUE2_CPU_ID	5
#define CMMT_CMPL_QUE3_CPU_ID	5

#define RECYCLE_QUE_CPU_ID	5

#define DVL_INFO_UPDT_REQ_QUE_CPU_ID	5
#define DVL_INFO_UPDT_CPL_QUE_CPU_ID	5

#define PDA_GEN_QUE0_CPU_ID	5
#define PDA_GEN_QUE1_CPU_ID	5
#define PDA_GEN_QUE2_CPU_ID	5
#define PDA_GEN_QUE3_CPU_ID	5
#define PDA_GEN_QUE4_CPU_ID	5
#define PDA_GEN_QUE5_CPU_ID	5
#define PDA_GEN_QUE6_CPU_ID	5
#define PDA_GEN_QUE7_CPU_ID	5

#define PDA_GEN_LOC0_CPU_ID	5
#define PDA_GEN_LOC1_CPU_ID	5

#define PDA_GEN_RSP0_QUE0_CPU_ID	5
#define PDA_GEN_RSP1_QUE0_CPU_ID	5
#define PDA_GEN_RSP0_QUE1_CPU_ID	5 // not ready
#define PDA_GEN_RSP1_QUE1_CPU_ID	5 // not ready
#define PDA_GEN_RSP0_QUE2_CPU_ID	5
#define PDA_GEN_RSP1_QUE2_CPU_ID	5
#define PDA_GEN_RSP0_QUE3_CPU_ID	5
#define PDA_GEN_RSP1_QUE3_CPU_ID	5
#define PDA_GEN_RSP0_QUE4_CPU_ID	5
#define PDA_GEN_RSP1_QUE4_CPU_ID	5
#define PDA_GEN_RSP0_QUE5_CPU_ID	5
#define PDA_GEN_RSP1_QUE5_CPU_ID	5
#define PDA_GEN_RSP0_QUE6_CPU_ID	5
#define PDA_GEN_RSP1_QUE6_CPU_ID	5
#define PDA_GEN_RSP0_QUE7_CPU_ID	5
#define PDA_GEN_RSP1_QUE7_CPU_ID	5

#define STATUS_SRCH_REQ_QUE_CPU_ID	5
#define STATUS_SRCH_RSP_QUE_CPU_ID	5
#define STATUS_FET_REQ_QUE_CPU_ID	5
#define STATUS_FET_RSP_QUE_CPU_ID	5
#define STATUS_CNT_NOTIFY_QUE_CPU_ID	5
#endif
