/*
 *
 * >- This file is generated by the register_parser.py, please do not modify. -<
 *
 */
#ifndef _SPI_REGISTER_H_
#define _SPI_REGISTER_H_

#define SPI_STATUS_REGISTER                      0x00000000
#define   SPI_FSM_ST_MASK                        0x00001f00
#define   SPI_FSM_ST_SHIFT                                8
#define   SPI_TRAN_MASK                          0x00000010
#define   SPI_TRAN_SHIFT                                  4
#define   SPI_TRAN_DONE_MASK                     0x00000008
#define   SPI_TRAN_DONE_SHIFT                             3
#define   SPI_ATLOAD_DISABLE_MASK                0x00000004
#define   SPI_ATLOAD_DISABLE_SHIFT                        2
#define   SPI_ATLOAD_SIGN_ERR_MASK               0x00000002
#define   SPI_ATLOAD_SIGN_ERR_SHIFT                       1
#define   SPI_ATLOAD_DONE_MASK                   0x00000001
#define   SPI_ATLOAD_DONE_SHIFT                           0

typedef union {
	u32 all;
	struct {
		u32 spi_atload_done:1;
		u32 spi_atload_sign_err:1;
		u32 spi_atload_disable:1;
		u32 spi_tran_done:1;
		u32 spi_tran:1;
		u32 rsvd_5:3;
		u32 spi_fsm_st:5;
		u32 rsvd_13:19;
	} b;
} spi_status_register_t;

#define SPI_CONTROL_REGISTER_1                   0x00000004
#define   SPI_SW_RST_MASK                        0x00000002
#define   SPI_SW_RST_SHIFT                                1
#define   SPI_TRAN_ST_MASK                       0x00000001
#define   SPI_TRAN_ST_SHIFT                               0

typedef union {
	u32  all;
	struct {
		u32  spi_tran_st:1;
		u32  spi_sw_rst:1;
		u32  rsvd_2:30;
    } b;
} spi_control_register_1_t;

#define SPI_STATUS_REGISTER_2                    0x00000008
#define   SPI_SCK_SEL_MASK                       0x0f000000
#define   SPI_SCK_SEL_SHIFT                              24
#define   SPI_BR_DIV_MASK                        0x00ffff00
#define   SPI_BR_DIV_SHIFT                                8
#define   SPI_TRAN_DB_LEN_MASK                   0x000000c0
#define   SPI_TRAN_DB_LEN_SHIFT                           6
#define   SPI_TRAN_TP_SEL_MASK                   0x00000030
#define   SPI_TRAN_TP_SEL_SHIFT                           4
#define   SPI_RX_RIS_SEL_MASK                    0x00000008
#define   SPI_RX_RIS_SEL_SHIFT                            3
#define   SPI_TX_RIS_SEL_MASK                    0x00000004
#define   SPI_TX_RIS_SEL_SHIFT                            2
#define   SPI_RW_CTRL_MASK                       0x00000002
#define   SPI_RW_CTRL_SHIFT                               1
#define   SPI_INT_EN_MASK                        0x00000001
#define   SPI_INT_EN_SHIFT                                0

typedef union {
	u32  all;
    struct {
		u32  spi_int_en:1;
		u32  spi_rw_ctrl:1;
		u32  spi_tx_ris_sel:1;
		u32  spi_rx_ris_sel:1;
		u32  spi_tran_tp_sel:2;
		u32  spi_tran_db_len:2;
		u32  spi_br_div:16;
		u32  spi_sck_sel:4;
		u32  rsvd_28:4;
    } b;
} spi_status_register_2_t;

#define SPI_COMMAND_REGISTER                     0x0000000c
#define   SPI_INST_MASK                          0xff000000
#define   SPI_INST_SHIFT                                 24
#define   SPI_TX_ADDR_MASK                       0x00ffffff
#define   SPI_TX_ADDR_SHIFT                               0

typedef union {
	u32  all;
    struct {
		u32  spi_tx_addr:24;
		u32  spi_inst:8;
    } b;
} spi_command_register_t;

#define SPI_TX_DATA_REGISTER                     0x00000010
#define   SPI_TX_DATA_BYTE0_MASK                 0xff000000
#define   SPI_TX_DATA_BYTE0_SHIFT                        24
#define   SPI_TX_DATA_BYTE1_MASK                 0x00ff0000
#define   SPI_TX_DATA_BYTE1_SHIFT                        16
#define   SPI_TX_DATA_BYTE2_MASK                 0x0000ff00
#define   SPI_TX_DATA_BYTE2_SHIFT                         8
#define   SPI_TX_DATA_BYTE3_MASK                 0x000000ff
#define   SPI_TX_DATA_BYTE3_SHIFT                         0

typedef union {
	u32  all;
	struct {
		u32  spi_tx_data_byte3:8;
		u32  spi_tx_data_byte2:8;
		u32  spi_tx_data_byte1:8;
		u32  spi_tx_data_byte0:8;
	} b;
} spi_tx_data_register_t;

#define SPI_RX_DATA_REGISTER                     0x00000014
#define   SPI_RX_DATA_BYTE0_MASK                 0xff000000
#define   SPI_RX_DATA_BYTE0_SHIFT                        24
#define   SPI_RX_DATA_BYTE1_MASK                 0x00ff0000
#define   SPI_RX_DATA_BYTE1_SHIFT                        16
#define   SPI_RX_DATA_BYTE2_MASK                 0x0000ff00
#define   SPI_RX_DATA_BYTE2_SHIFT                         8
#define   SPI_RX_DATA_BYTE3_MASK                 0x000000ff
#define   SPI_RX_DATA_BYTE3_SHIFT                         0
typedef union {
	u32  all;
	struct {
		u32  spi_rx_data_byte3:8;
		u32  spi_rx_data_byte2:8;
		u32  spi_rx_data_byte1:8;
		u32  spi_rx_data_byte0:8;
	} b;
} spi_rx_data_register_t;


#ifndef REG_GFLD
# define REG_GFLD(val, FLD) (((uint32_t)(val) &  FLD ## _MASK) >> FLD ## _SHIFT)
# define REG_SFLD(val, FLD) (((uint32_t)(val) << FLD ## _SHIFT) & FLD ## _MASK)
# define REG_RMW(o, n, FLD) ((((uint32_t)(o) & ~ FLD ## _MASK)) | (((uint32_t)(n) << FLD ## _SHIFT)))
#endif

typedef struct {
    /* 0x0000 */ spi_status_register_t spi_status_register;
    /* 0x0004 */ spi_control_register_1_t spi_control_register_1;
    /* 0x0008 */ spi_status_register_2_t spi_status_register_2;
    /* 0x000c */ spi_command_register_t spi_command_register;
    /* 0x0010 */ spi_tx_data_register_t spi_tx_data_register;
    /* 0x0014 */ spi_rx_data_register_t spi_rx_data_register;
} spi_register_regs_t;

#define SCORE_BOARD_ADDR 0x8000
typedef union {
	u32  all;
    struct {
		u32  fsm:8;
		u32  ce:8;
		u32  pagenumber:16;
    } b;
} spi_score_board_t;


typedef union{
	u32 all;
	struct{
		u32   signature:24;
		u32   Cpu_ID_n:8;
	} b;
} spi_savelog_info_t;

typedef struct{
	u32 ddr_buf_address[MPC];
	u32 byte_cnt[MPC];
} spi_buf_info_t;

enum spi_cmd_t {
    SPI_PP     = 0x02, //page program sequence
    SPI_READ   = 0x03, //read data bytes sequence
    SPI_RDSR   = 0x05, //read status
    SPI_WREN   = 0x06, //write enable
    SPI_RDSCUR = 0x2B,
    SPI_BE32K  = 0x52, //block erase 32kB
    SPI_BE4K   = 0x20, //Sector erase 4kB
    SPI_CE     = 0x60, //chip erase
    SPI_RDID   = 0x9F, //read ID

};

#define SPI_CTRL_BASE 0xC0051000
#define SPI_TX_XFER_CLEAN spi_tx_data(0x0);


#endif /* rev 0 */

