//-----------------------------------------------------------------------------
//
//		Copyright(c) 2016-2019 Innogrit Corporation
//			All Rights reserved.
//
// The confidential and proprietary information contained in this file may
// only be used by a person authorized under and to the extent permitted
// by a subsisting licensing agreement from Innogrit Corporation.
//
//-----------------------------------------------------------------------------

/*
 *
 * >- Project: Rainier
 *
 * >- This file is generated by the register_parser.py, please do not modify. -<
 *
 */
#ifndef _ECCU_BCH_DEC_REGISTER_H_
#define _ECCU_BCH_DEC_REGISTER_H_

#define BCH_DEC_CTRS_REG0                        0x00000000
#define   BCH_DEC_CW_FND_MASK                    0xf0000000
#define   BCH_DEC_CW_FND_SHIFT                           28
#define   BCH_DEC_CW_FND_INT_MASK                0x0f000000
#define   BCH_DEC_CW_FND_INT_SHIFT                       24
#define   BCH_DEC_ERR_OVRTHD_CW_CNT_CLR_MASK     0x00000008
#define   BCH_DEC_ERR_OVRTHD_CW_CNT_CLR_SHIFT             3
#define   BCH_DEC_DIS_MASK                       0x00000004
#define   BCH_DEC_DIS_SHIFT                               2
#define   BCH_DEC_BYPASS_MASK                    0x00000002
#define   BCH_DEC_BYPASS_SHIFT                            1
#define   BCH_DEC_RESET_MASK                     0x00000001
#define   BCH_DEC_RESET_SHIFT                             0

typedef union {
    u32 all;
    struct {
        u32 bch_dec_reset:1;
        u32 bch_dec_bypass:1;
        u32 bch_dec_dis:1;
        u32 bch_dec_err_ovrthd_cw_cnt_clr:1;
        u32 rsvd_4:20;
        u32 bch_dec_cw_fnd_int:4;
        u32 bch_dec_cw_fnd:4;
    } b;
} bch_dec_ctrs_reg0_t;

#define BCH_DEC_CTRS_REG1                        0x00000004
#define   BCH_DEC_ERR_CNT_1TO0_MASK              0xffff0000
#define   BCH_DEC_ERR_CNT_1TO0_SHIFT                     16
#define   BCH_DEC_ERR_CNT_0TO1_MASK              0x0000ffff
#define   BCH_DEC_ERR_CNT_0TO1_SHIFT                      0

typedef union {
    u32 all;
    struct {
        u32 bch_dec_err_cnt_0to1:16;
        u32 bch_dec_err_cnt_1to0:16;
    } b;
} bch_dec_ctrs_reg1_t;

#define BCH_DEC_CTRS_REG2                        0x00000008
#define   BCH_DEC_ERR_OVRTHD_CW_CNT_MASK         0xffffffff
#define   BCH_DEC_ERR_OVRTHD_CW_CNT_SHIFT                 0

typedef union {
    u32 all;
    struct {
        u32 bch_dec_err_ovrthd_cw_cnt:32;
    } b;
} bch_dec_ctrs_reg2_t;

#define BCH_DEC_CTRS_REG3                        0x0000000c

typedef union {
    u32 all;
    struct {
        u32 rsvd_0:32;
    } b;
} bch_dec_ctrs_reg3_t;

#define BCH_DEC_CTRS_REG4                        0x00000010
#define   BCH_DEC_ERR_THD_MASK                   0x00ff0000
#define   BCH_DEC_ERR_THD_SHIFT                          16
#define   BCH_DEC_FORCE_CW_FAIL_MASK             0x0000000f
#define   BCH_DEC_FORCE_CW_FAIL_SHIFT                     0

typedef union {
    u32 all;
    struct {
        u32 bch_dec_force_cw_fail:4;
        u32 rsvd_4:12;
        u32 bch_dec_err_thd:8;
        u32 rsvd_24:8;
    } b;
} bch_dec_ctrs_reg4_t;

#define BCH_DEC_DBG_REG                          0x00000014
#define   BCH_DEC_DBG_STATUS_MASK                0xffff0000
#define   BCH_DEC_DBG_STATUS_SHIFT                       16
#define   BCH_DEC_DBG_SEL_MASK                   0x0000ffff
#define   BCH_DEC_DBG_SEL_SHIFT                           0

typedef union {
    u32 all;
    struct {
        u32 bch_dec_dbg_sel:16;
        u32 bch_dec_dbg_status:16;
    } b;
} bch_dec_dbg_reg_t;

#define BCH_DEC_MEM_REG0                         0x00000018
#define   BCH_DEC_CW_MEM_RTSEL_MASK              0x00000030
#define   BCH_DEC_CW_MEM_RTSEL_SHIFT                      4
#define   BCH_DEC_CW_MEM_WTSEL_MASK              0x0000000c
#define   BCH_DEC_CW_MEM_WTSEL_SHIFT                      2
#define   BCH_DEC_MEM_PWDN_MASK                  0x00000002
#define   BCH_DEC_MEM_PWDN_SHIFT                          1
typedef union {
    u32 all;
    struct {
        u32 rsvd_0:1;
        u32 bch_dec_mem_pwdn:1;
        u32 bch_dec_cw_mem_wtsel:2;
        u32 bch_dec_cw_mem_rtsel:2;
        u32 rsvd_6:26;
    } b;
} bch_dec_mem_reg0_t;


#ifndef REG_GFLD
# define REG_GFLD(val, FLD) (((u32)(val) &  FLD ## _MASK) >> FLD ## _SHIFT)
# define REG_SFLD(val, FLD) (((u32)(val) << FLD ## _SHIFT) & FLD ## _MASK)
# define REG_RMW(o, n, FLD) ((((u32)(o) & ~ FLD ## _MASK)) | (((u32)(n) << FLD ## _SHIFT)))
#endif

typedef struct {
    /* 0x0000 */ bch_dec_ctrs_reg0_t bch_dec_ctrs_reg0;
    /* 0x0004 */ bch_dec_ctrs_reg1_t bch_dec_ctrs_reg1;
    /* 0x0008 */ bch_dec_ctrs_reg2_t bch_dec_ctrs_reg2;
    /* 0x000c */ bch_dec_ctrs_reg3_t bch_dec_ctrs_reg3;
    /* 0x0010 */ bch_dec_ctrs_reg4_t bch_dec_ctrs_reg4;
    /* 0x0014 */ bch_dec_dbg_reg_t bch_dec_dbg_reg;
    /* 0x0018 */ bch_dec_mem_reg0_t bch_dec_mem_reg0;
} eccu_bch_dec_regs_t;


#endif /* rev 1002 */