//-----------------------------------------------------------------------------
//
//		Copyright(c) 2016-2019 Innogrit Corporation
//			All Rights reserved.
//
// The confidential and proprietary information contained in this file may
// only be used by a person authorized under and to the extent permitted
// by a subsisting licensing agreement from Innogrit Corporation.
//
//-----------------------------------------------------------------------------

/*
 *
 * >- Project: Rainier
 *
 * >- This file is generated by the register_parser.py, please do not modify. -<
 *
 */
#ifndef _ECCU_BCH_ENC_REGISTER_H_
#define _ECCU_BCH_ENC_REGISTER_H_

#define BCH_ENC_CTRL_REG0                        0x00000000
#define   BCH_ENC_BYPASS_MASK                    0x00000002
#define   BCH_ENC_BYPASS_SHIFT                            1
#define   BCH_ENC_RESET_MASK                     0x00000001
#define   BCH_ENC_RESET_SHIFT                             0

typedef union {
    u32 all;
    struct {
        u32 bch_enc_reset:1;
        u32 bch_enc_bypass:1;
        u32 rsvd_2:30;
    } b;
} bch_enc_ctrl_reg0_t;

#define BCH_ENC_STATUS_REG0                      0x00000004

typedef union {
    u32 all;
    struct {
        u32 rsvd_0:32;
    } b;
} bch_enc_status_reg0_t;

#define BCH_ENC_DBG_REG                          0x00000008
#define   BCH_ENC_DBG_STATUS_MASK                0xffff0000
#define   BCH_ENC_DBG_STATUS_SHIFT                       16
#define   BCH_ENC_DBG_SEL_MASK                   0x0000ffff
#define   BCH_ENC_DBG_SEL_SHIFT                           0
typedef union {
    u32 all;
    struct {
        u32 bch_enc_dbg_sel:16;
        u32 bch_enc_dbg_status:16;
    } b;
} bch_enc_dbg_reg_t;


#ifndef REG_GFLD
# define REG_GFLD(val, FLD) (((u32)(val) &  FLD ## _MASK) >> FLD ## _SHIFT)
# define REG_SFLD(val, FLD) (((u32)(val) << FLD ## _SHIFT) & FLD ## _MASK)
# define REG_RMW(o, n, FLD) ((((u32)(o) & ~ FLD ## _MASK)) | (((u32)(n) << FLD ## _SHIFT)))
#endif

typedef struct {
    /* 0x0000 */ bch_enc_ctrl_reg0_t bch_enc_ctrl_reg0;
    /* 0x0004 */ bch_enc_status_reg0_t bch_enc_status_reg0;
    /* 0x0008 */ bch_enc_dbg_reg_t bch_enc_dbg_reg;
} eccu_bch_enc_regs_t;


#endif /* rev 1002 */