//-----------------------------------------------------------------------------
//
//		Copyright(c) 2016-2019 Innogrit Corporation
//			All Rights reserved.
//
// The confidential and proprietary information contained in this file may
// only be used by a person authorized under and to the extent permitted
// by a subsisting licensing agreement from Innogrit Corporation.
//
//-----------------------------------------------------------------------------

/*
 *
 * >- Project: Rainier
 *
 * >- This file is generated by the register_parser.py, please do not modify. -<
 *
 */
#ifndef _NCB_MISC_REGISTER_H_
#define _NCB_MISC_REGISTER_H_

#define MEM_EXT_ACC_REG0                         0x00000000
#define   MEM_EXT_ACC_SEL_ID_MASK                0x0000ff00
#define   MEM_EXT_ACC_SEL_ID_SHIFT                        8
#define   MEM_EXT_ACC_MDEC_SEL_MASK              0x00000002
#define   MEM_EXT_ACC_MDEC_SEL_SHIFT                      1
#define   MEM_EXT_ACC_EN_MASK                    0x00000001
#define   MEM_EXT_ACC_EN_SHIFT                            0

typedef union {
    u32 all;
    struct {
        u32 mem_ext_acc_en:1;
        u32 mem_ext_acc_mdec_sel:1;
        u32 rsvd_2:6;
        u32 mem_ext_acc_sel_id:8;
        u32 rsvd_16:16;
    } b;
} mem_ext_acc_reg0_t;

#define MEM_EXT_ACC_REG1                         0x00000004
#define   MEM_EXT_ACC_DW_SEL_MASK                0x003f0000
#define   MEM_EXT_ACC_DW_SEL_SHIFT                       16
#define   MEM_EXT_ACC_ADR_MASK                   0x00003fff
#define   MEM_EXT_ACC_ADR_SHIFT                           0

typedef union {
    u32 all;
    struct {
        u32 mem_ext_acc_adr:14;
        u32 rsvd_14:2;
        u32 mem_ext_acc_dw_sel:6;
        u32 rsvd_22:10;
    } b;
} mem_ext_acc_reg1_t;

#define MEM_EXT_ACC_REG2                         0x00000008
#define   MEM_EXT_ACC_DOUT_MASK                  0xffffffff
#define   MEM_EXT_ACC_DOUT_SHIFT                          0

typedef union {
    u32 all;
    struct {
        u32 mem_ext_acc_dout:32;
    } b;
} mem_ext_acc_reg2_t;

#define NCB_PIN_DBG_REG                          0x0000000c
#define   NCB_PIN_DBG_SEL_MASK                   0x0000001f
#define   NCB_PIN_DBG_SEL_SHIFT                           0

typedef union {
    u32 all;
    struct {
        u32 ncb_pin_dbg_sel:5;
        u32 rsvd_5:27;
    } b;
} ncb_pin_dbg_reg_t;

#define FSPM_DEBUG_REG                           0x00000010
#define   FSPM_DBG_STATUS_MASK                   0xffff0000
#define   FSPM_DBG_STATUS_SHIFT                          16
#define   FSPM_DBG_SEL_MASK                      0x0000ffff
#define   FSPM_DBG_SEL_SHIFT                              0
typedef union {
    u32 all;
    struct {
        u32 fspm_dbg_sel:16;
        u32 fspm_dbg_status:16;
    } b;
} fspm_debug_reg_t;


#ifndef REG_GFLD
# define REG_GFLD(val, FLD) (((u32)(val) &  FLD ## _MASK) >> FLD ## _SHIFT)
# define REG_SFLD(val, FLD) (((u32)(val) << FLD ## _SHIFT) & FLD ## _MASK)
# define REG_RMW(o, n, FLD) ((((u32)(o) & ~ FLD ## _MASK)) | (((u32)(n) << FLD ## _SHIFT)))
#endif

typedef struct {
    /* 0x0000 */ mem_ext_acc_reg0_t mem_ext_acc_reg0;
    /* 0x0004 */ mem_ext_acc_reg1_t mem_ext_acc_reg1;
    /* 0x0008 */ mem_ext_acc_reg2_t mem_ext_acc_reg2;
    /* 0x000c */ ncb_pin_dbg_reg_t ncb_pin_dbg_reg;
    /* 0x0010 */ fspm_debug_reg_t fspm_debug_reg;
} ncb_misc_regs_t;


#endif /* rev 1000 */