//-----------------------------------------------------------------------------
//
//		Copyright(c) 2016-2019 Innogrit Corporation
//			All Rights reserved.
//
// The confidential and proprietary information contained in this file may
// only be used by a person authorized under and to the extent permitted
// by a subsisting licensing agreement from Innogrit Corporation.
//
//-----------------------------------------------------------------------------

/*
 *
 * >- Project: Rainier
 *
 * >- This file is generated by the register_parser.py, please do not modify. -<
 *
 */
#ifndef _NDPHY_REGISTER_H_
#define _NDPHY_REGISTER_H_

#define NPHY_CTRL_REG0                           0x00000000
#define   NPHY_NO_DQS_ERR_MASK                   0x80000000
#define   NPHY_NO_DQS_ERR_SHIFT                          31
#define   NPHY_IO_STRB_EN_MASK                   0x00080000
#define   NPHY_IO_STRB_EN_SHIFT                          19
#define   NPHY_QS_GATE_DIS_MASK                  0x00040000
#define   NPHY_QS_GATE_DIS_SHIFT                         18
#define   NPHY_SYNC_RDPTR_DLY_MASK               0x00038000
#define   NPHY_SYNC_RDPTR_DLY_SHIFT                      15
#define   NPHY_DIFF_FORCE_VAL_MASK               0x00006000
#define   NPHY_DIFF_FORCE_VAL_SHIFT                      13
#define   NPHY_DIFF_EN_MASK                      0x00001000
#define   NPHY_DIFF_EN_SHIFT                             12
#define   NPHY_FRDST_DLY_MASK                    0x00000300
#define   NPHY_FRDST_DLY_SHIFT                            8
#define   NPHY_WR_LD_FLIP_MASK                   0x00000040
#define   NPHY_WR_LD_FLIP_SHIFT                           6
#define   NPHY_DQS_CNT_RST_MASK                  0x00000020
#define   NPHY_DQS_CNT_RST_SHIFT                          5
#define   NPHY_RD_PTR_RST_MASK                   0x00000010
#define   NPHY_RD_PTR_RST_SHIFT                           4
#define   NPHY_WRST_SEL_MASK                     0x0000000c
#define   NPHY_WRST_SEL_SHIFT                             2
#define   NPHY_SYNC_EN_MASK                      0x00000002
#define   NPHY_SYNC_EN_SHIFT                              1
#define   NPHY_SYNC_RSTN_MASK                    0x00000001
#define   NPHY_SYNC_RSTN_SHIFT                            0

typedef union {
    u32 all;
    struct {
        u32 nphy_sync_rstn:1;
        u32 nphy_sync_en:1;
        u32 nphy_wrst_sel:2;
        u32 nphy_rd_ptr_rst:1;
        u32 nphy_dqs_cnt_rst:1;
        u32 nphy_wr_ld_flip:1;
        u32 rsvd_7:1;
        u32 nphy_frdst_dly:2;
        u32 rsvd_10:2;
        u32 nphy_diff_en:1;
        u32 nphy_diff_force_val:2;
        u32 nphy_sync_rdptr_dly:3;
        u32 nphy_qs_gate_dis:1;
        u32 nphy_io_strb_en:1;
        u32 rsvd_20:11;
        u32 nphy_no_dqs_err:1;
    } b;
} nphy_ctrl_reg0_t;

#define NPHY_CTRL_REG1                           0x00000004
#define   NPHY_QS_MIRROR_MASK                    0x80000000
#define   NPHY_QS_MIRROR_SHIFT                           31
#define   NPHY_DQ_FLIP_MASK                      0x40000000
#define   NPHY_DQ_FLIP_SHIFT                             30
#define   NPHY_VREF_SEL2_MASK                    0x20000000
#define   NPHY_VREF_SEL2_SHIFT                           29
#define   NPHY_VREF_SEL1_MASK                    0x10000000
#define   NPHY_VREF_SEL1_SHIFT                           28
#define   NPHY_VREF_SEL0_MASK                    0x08000000
#define   NPHY_VREF_SEL0_SHIFT                           27
#define   NPHY_ASYNC_RDPTR_DLY_MASK              0x07000000
#define   NPHY_ASYNC_RDPTR_DLY_SHIFT                     24
#define   NPHY_ASYNC_RE2QS_DLY_MASK              0x00ff0000
#define   NPHY_ASYNC_RE2QS_DLY_SHIFT                     16
#define   NPHY_SYNC_RE2QS_DLY_MASK               0x0000ff00
#define   NPHY_SYNC_RE2QS_DLY_SHIFT                       8
#define   NPHY_RE2QS_GATE_DLY_MASK               0x000000ff
#define   NPHY_RE2QS_GATE_DLY_SHIFT                       0

typedef union {
    u32 all;
    struct {
        u32 nphy_re2qs_gate_dly:8;
        u32 nphy_sync_re2qs_dly:8;
        u32 nphy_async_re2qs_dly:8;
        u32 nphy_async_rdptr_dly:3;
        u32 nphy_vref_sel0:1;
        u32 nphy_vref_sel1:1;
        u32 nphy_vref_sel2:1;
        u32 nphy_dq_flip:1;
        u32 nphy_qs_mirror:1;
    } b;
} nphy_ctrl_reg1_t;

#define DTPHY_CTRL_REG0                          0x00000008
#define   DTPHY_TDIE_MASK                        0xff000000
#define   DTPHY_TDIE_SHIFT                               24
#define   DTPHY_LPBK_DLY_MASK                    0x00f00000
#define   DTPHY_LPBK_DLY_SHIFT                           20
#define   DTPHY_TDOE_MASK                        0x00040000
#define   DTPHY_TDOE_SHIFT                               18
#define   DTPHY_TMS_MASK                         0x00020000
#define   DTPHY_TMS_SHIFT                                17
#define   DTPHY_ASYNC_MODE_MASK                  0x00010000
#define   DTPHY_ASYNC_MODE_SHIFT                         16
#define   DTPHY_QS_GATE_DLY_SEL_MASK             0x0000ff00
#define   DTPHY_QS_GATE_DLY_SEL_SHIFT                     8
#define   DTPHY_ASYNC_DLY_SEL_MASK               0x000000ff
#define   DTPHY_ASYNC_DLY_SEL_SHIFT                       0

typedef union {
    u32 all;
    struct {
        u32 dtphy_async_dly_sel:8;
        u32 dtphy_qs_gate_dly_sel:8;
        u32 dtphy_async_mode:1;
        u32 dtphy_tms:1;
        u32 dtphy_tdoe:1;
        u32 rsvd_19:1;
        u32 dtphy_lpbk_dly:4;
        u32 dtphy_tdie:8;
    } b;
} dtphy_ctrl_reg0_t;

#define DTPHY_CTRL_REG1                          0x0000000c
#define   DTPHY_LPBK_RDPTR_DLY_MASK              0x07000000
#define   DTPHY_LPBK_RDPTR_DLY_SHIFT                     24
#define   PWRDWN_MASK                            0x00ff0000
#define   PWRDWN_SHIFT                                   16
#define   DTPHY_NVDDR_MASK                       0x0000ff00
#define   DTPHY_NVDDR_SHIFT                               8
#define   DTPHY_DQ_RCVTYPE_MASK                  0x000000ff
#define   DTPHY_DQ_RCVTYPE_SHIFT                          0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dq_rcvtype:8;
        u32 dtphy_nvddr:8;
        u32 pwrdwn:8;
        u32 dtphy_lpbk_rdptr_dly:3;
        u32 rsvd_27:5;
    } b;
} dtphy_ctrl_reg1_t;

#define DTPHY_CTRL_REG2                          0x00000010
#define   DTPHY_PU_MASK                          0xff000000
#define   DTPHY_PU_SHIFT                                 24
#define   DTPHY_PD_MASK                          0x00ff0000
#define   DTPHY_PD_SHIFT                                 16
#define   DTPHY_DQ_SLR_MASK                      0x0000ff00
#define   DTPHY_DQ_SLR_SHIFT                              8
#define   DTPHY_DQ_MS_MASK                       0x000000ff
#define   DTPHY_DQ_MS_SHIFT                               0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dq_ms:8;
        u32 dtphy_dq_slr:8;
        u32 dtphy_pd:8;
        u32 dtphy_pu:8;
    } b;
} dtphy_ctrl_reg2_t;

#define DTPHY_CTRL_REG3                          0x00000014
#define   DTPHY_DLL_PHSEL1_MASK                  0x0fc00000
#define   DTPHY_DLL_PHSEL1_SHIFT                         22
#define   DTPHY_DLL_LOCKED_MASK                  0x00200000
#define   DTPHY_DLL_LOCKED_SHIFT                         21
#define   DTPHY_DLL_UPDATE_EN_MASK               0x00100000
#define   DTPHY_DLL_UPDATE_EN_SHIFT                      20
#define   DTPHY_DLL_RSTB_MASK                    0x00020000
#define   DTPHY_DLL_RSTB_SHIFT                           17
#define   DTPHY_DLL_TEST_EN_MASK                 0x00010000
#define   DTPHY_DLL_TEST_EN_SHIFT                        16
#define   DTPHY_DLL_PHSEL0_MASK                  0x0000fc00
#define   DTPHY_DLL_PHSEL0_SHIFT                         10
#define   DTPHY_DLL_BYPASS_EN_MASK               0x00000200
#define   DTPHY_DLL_BYPASS_EN_SHIFT                       9
#define   DTPHY_DLL_DLY_TEST_MASK                0x000001ff
#define   DTPHY_DLL_DLY_TEST_SHIFT                        0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dll_dly_test:9;
        u32 dtphy_dll_bypass_en:1;
        u32 dtphy_dll_phsel0:6;
        u32 dtphy_dll_test_en:1;
        u32 dtphy_dll_rstb:1;
        u32 rsvd_18:2;
        u32 dtphy_dll_update_en:1;
        u32 dtphy_dll_locked:1;
        u32 dtphy_dll_phsel1:6;
        u32 rsvd_28:4;
    } b;
} dtphy_ctrl_reg3_t;

#define DTPHY_CTRL_REG4                          0x00000018
#define   DTPHY_RSVVD_INT_MASK                   0x000ff000
#define   DTPHY_RSVVD_INT_SHIFT                          12
#define   DTPHY_FC_TRIM0_MASK                    0x00000200
#define   DTPHY_FC_TRIM0_SHIFT                            9
#define   DTPHY_FC_TRIM1_MASK                    0x00000100
#define   DTPHY_FC_TRIM1_SHIFT                            8
#define   DTPHY_QS_DIFF_EN_MASK                  0x00000080
#define   DTPHY_QS_DIFF_EN_SHIFT                          7
#define   DTPHY_QS_MIRROR_MASK                   0x00000040
#define   DTPHY_QS_MIRROR_SHIFT                           6
#define   DTPHY_FC_ODT_EN_MASK                   0x00000020
#define   DTPHY_FC_ODT_EN_SHIFT                           5
#define   DTPHY_FC_PSTR_MASK                     0x0000001f
#define   DTPHY_FC_PSTR_SHIFT                             0

typedef union {
    u32 all;
    struct {
        u32 dtphy_fc_pstr:5;
        u32 dtphy_fc_odt_en:1;
        u32 dtphy_qs_mirror:1;
        u32 dtphy_qs_diff_en:1;
        u32 dtphy_fc_trim1:1;
        u32 dtphy_fc_trim0:1;
        u32 rsvd_10:2;
        u32 dtphy_rsvvd_int:8;
        u32 rsvd_20:12;
    } b;
} dtphy_ctrl_reg4_t;

#define DTPHY_CTRL_REG5                          0x0000001c
#define   DTPHY_DSTR3_MASK                       0xff000000
#define   DTPHY_DSTR3_SHIFT                              24
#define   DTPHY_DSTR2_MASK                       0x00ff0000
#define   DTPHY_DSTR2_SHIFT                              16
#define   DTPHY_DSTR1_MASK                       0x0000ff00
#define   DTPHY_DSTR1_SHIFT                               8
#define   DTPHY_DSTR0_MASK                       0x000000ff
#define   DTPHY_DSTR0_SHIFT                               0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dstr0:8;
        u32 dtphy_dstr1:8;
        u32 dtphy_dstr2:8;
        u32 dtphy_dstr3:8;
    } b;
} dtphy_ctrl_reg5_t;

#define DTPHY_CTRL_REG6                          0x00000020
#define   DTPHY_ODT_SEL3_MASK                    0xff000000
#define   DTPHY_ODT_SEL3_SHIFT                           24
#define   DTPHY_ODT_SEL2_MASK                    0x00ff0000
#define   DTPHY_ODT_SEL2_SHIFT                           16
#define   DTPHY_ODT_SEL1_MASK                    0x0000ff00
#define   DTPHY_ODT_SEL1_SHIFT                            8
#define   DTPHY_ODT_SEL0_MASK                    0x000000ff
#define   DTPHY_ODT_SEL0_SHIFT                            0

typedef union {
    u32 all;
    struct {
        u32 dtphy_odt_sel0:8;
        u32 dtphy_odt_sel1:8;
        u32 dtphy_odt_sel2:8;
        u32 dtphy_odt_sel3:8;
    } b;
} dtphy_ctrl_reg6_t;

#define DTPHY_CTRL_REG7                          0x00000024
#define   DTPHY_CTRL_REG7_RSVVD_MASK             0xffffffff
#define   DTPHY_CTRL_REG7_RSVVD_SHIFT                     0

typedef union {
    u32 all;
    struct {
        u32 dtphy_ctrl_reg7_rsvvd:32;
    } b;
} dtphy_ctrl_reg7_t;

#define DTPHY_CTRL_REG8                          0x00000028
#define   DTPHY_CTRL_REG8_RSVVD_MASK             0xffffffff
#define   DTPHY_CTRL_REG8_RSVVD_SHIFT                     0

typedef union {
    u32 all;
    struct {
        u32 dtphy_ctrl_reg8_rsvvd:32;
    } b;
} dtphy_ctrl_reg8_t;

#define DTPHY_CTRL_REG9                          0x0000002c
#define   DTPHY_CLK2X_DQD_DLY7_MASK              0xff000000
#define   DTPHY_CLK2X_DQD_DLY7_SHIFT                     24
#define   DTPHY_CLK2X_DQD_DLY6_MASK              0x00ff0000
#define   DTPHY_CLK2X_DQD_DLY6_SHIFT                     16
#define   DTPHY_CLK2X_DQD_DLY5_MASK              0x0000ff00
#define   DTPHY_CLK2X_DQD_DLY5_SHIFT                      8
#define   DTPHY_CLK2X_DQD_DLY4_MASK              0x000000ff
#define   DTPHY_CLK2X_DQD_DLY4_SHIFT                      0

typedef union {
    u32 all;
    struct {
        u32 dtphy_clk2x_dqd_dly4:8;
        u32 dtphy_clk2x_dqd_dly5:8;
        u32 dtphy_clk2x_dqd_dly6:8;
        u32 dtphy_clk2x_dqd_dly7:8;
    } b;
} dtphy_ctrl_reg9_t;

#define DTPHY_CTRL_REG10                         0x00000030
#define   DTPHY_CLK2X_DQD_DLY3_MASK              0xff000000
#define   DTPHY_CLK2X_DQD_DLY3_SHIFT                     24
#define   DTPHY_CLK2X_DQD_DLY2_MASK              0x00ff0000
#define   DTPHY_CLK2X_DQD_DLY2_SHIFT                     16
#define   DTPHY_CLK2X_DQD_DLY1_MASK              0x0000ff00
#define   DTPHY_CLK2X_DQD_DLY1_SHIFT                      8
#define   DTPHY_CLK2X_DQD_DLY0_MASK              0x000000ff
#define   DTPHY_CLK2X_DQD_DLY0_SHIFT                      0

typedef union {
    u32 all;
    struct {
        u32 dtphy_clk2x_dqd_dly0:8;
        u32 dtphy_clk2x_dqd_dly1:8;
        u32 dtphy_clk2x_dqd_dly2:8;
        u32 dtphy_clk2x_dqd_dly3:8;
    } b;
} dtphy_ctrl_reg10_t;

#define DTPHY_CTRL_REG11                         0x00000034
#define   DTPHY_CLK2X_DQC_DLY7_MASK              0xff000000
#define   DTPHY_CLK2X_DQC_DLY7_SHIFT                     24
#define   DTPHY_CLK2X_DQC_DLY6_MASK              0x00ff0000
#define   DTPHY_CLK2X_DQC_DLY6_SHIFT                     16
#define   DTPHY_CLK2X_DQC_DLY5_MASK              0x0000ff00
#define   DTPHY_CLK2X_DQC_DLY5_SHIFT                      8
#define   DTPHY_CLK2X_DQC_DLY4_MASK              0x000000ff
#define   DTPHY_CLK2X_DQC_DLY4_SHIFT                      0

typedef union {
    u32 all;
    struct {
        u32 dtphy_clk2x_dqc_dly4:8;
        u32 dtphy_clk2x_dqc_dly5:8;
        u32 dtphy_clk2x_dqc_dly6:8;
        u32 dtphy_clk2x_dqc_dly7:8;
    } b;
} dtphy_ctrl_reg11_t;

#define DTPHY_CTRL_REG12                         0x00000038
#define   DTPHY_CLK2X_DQC_DLY3_MASK              0xff000000
#define   DTPHY_CLK2X_DQC_DLY3_SHIFT                     24
#define   DTPHY_CLK2X_DQC_DLY2_MASK              0x00ff0000
#define   DTPHY_CLK2X_DQC_DLY2_SHIFT                     16
#define   DTPHY_CLK2X_DQC_DLY1_MASK              0x0000ff00
#define   DTPHY_CLK2X_DQC_DLY1_SHIFT                      8
#define   DTPHY_CLK2X_DQC_DLY0_MASK              0x000000ff
#define   DTPHY_CLK2X_DQC_DLY0_SHIFT                      0

typedef union {
    u32 all;
    struct {
        u32 dtphy_clk2x_dqc_dly0:8;
        u32 dtphy_clk2x_dqc_dly1:8;
        u32 dtphy_clk2x_dqc_dly2:8;
        u32 dtphy_clk2x_dqc_dly3:8;
    } b;
} dtphy_ctrl_reg12_t;

#define DTPHY_CTRL_REG13                         0x0000003c
#define   DTPHY_QSP_TDIE_MASK                    0x00008000
#define   DTPHY_QSP_TDIE_SHIFT                           15
#define   DTPHY_QSP_PU_MASK                      0x00004000
#define   DTPHY_QSP_PU_SHIFT                             14
#define   DTPHY_QSP_PD_MASK                      0x00002000
#define   DTPHY_QSP_PD_SHIFT                             13
#define   DTPHY_QSP_RCVTYPE_MASK                 0x00001000
#define   DTPHY_QSP_RCVTYPE_SHIFT                        12
#define   DTPHY_QSP_SLR_MASK                     0x00000800
#define   DTPHY_QSP_SLR_SHIFT                            11
#define   DTPHY_QSP_MS_MASK                      0x00000400
#define   DTPHY_QSP_MS_SHIFT                             10
#define   DTPHY_QSP_PWRDWN_MASK                  0x00000200
#define   DTPHY_QSP_PWRDWN_SHIFT                          9
#define   DTPHY_QSP_NVDDR_MASK                   0x00000100
#define   DTPHY_QSP_NVDDR_SHIFT                           8
#define   DTPHY_QSN_TDIE_MASK                    0x00000080
#define   DTPHY_QSN_TDIE_SHIFT                            7
#define   DTPHY_QSN_PU_MASK                      0x00000040
#define   DTPHY_QSN_PU_SHIFT                              6
#define   DTPHY_QSN_PD_MASK                      0x00000020
#define   DTPHY_QSN_PD_SHIFT                              5
#define   DTPHY_QSN_RCVTYPE_MASK                 0x00000010
#define   DTPHY_QSN_RCVTYPE_SHIFT                         4
#define   DTPHY_QSN_SLR_MASK                     0x00000008
#define   DTPHY_QSN_SLR_SHIFT                             3
#define   DTPHY_QSN_MS_MASK                      0x00000004
#define   DTPHY_QSN_MS_SHIFT                              2
#define   DTPHY_QSN_PWRDWN_MASK                  0x00000002
#define   DTPHY_QSN_PWRDWN_SHIFT                          1
#define   DTPHY_QSN_NVDDR_MASK                   0x00000001
#define   DTPHY_QSN_NVDDR_SHIFT                           0

typedef union {
    u32 all;
    struct {
        u32 dtphy_qsn_nvddr:1;
        u32 dtphy_qsn_pwrdwn:1;
        u32 dtphy_qsn_ms:1;
        u32 dtphy_qsn_slr:1;
        u32 dtphy_qsn_rcvtype:1;
        u32 dtphy_qsn_pd:1;
        u32 dtphy_qsn_pu:1;
        u32 dtphy_qsn_tdie:1;
        u32 dtphy_qsp_nvddr:1;
        u32 dtphy_qsp_pwrdwn:1;
        u32 dtphy_qsp_ms:1;
        u32 dtphy_qsp_slr:1;
        u32 dtphy_qsp_rcvtype:1;
        u32 dtphy_qsp_pd:1;
        u32 dtphy_qsp_pu:1;
        u32 dtphy_qsp_tdie:1;
        u32 rsvd_16:16;
    } b;
} dtphy_ctrl_reg13_t;

#define DTPHY_CTRL_REG14                         0x00000040
#define   DTPHY_QSP_DSTR3_MASK                   0x80000000
#define   DTPHY_QSP_DSTR3_SHIFT                          31
#define   DTPHY_QSP_DSTR2_MASK                   0x40000000
#define   DTPHY_QSP_DSTR2_SHIFT                          30
#define   DTPHY_QSP_DSTR1_MASK                   0x20000000
#define   DTPHY_QSP_DSTR1_SHIFT                          29
#define   DTPHY_QSP_DSTR0_MASK                   0x10000000
#define   DTPHY_QSP_DSTR0_SHIFT                          28
#define   DTPHY_QSP_ODT_SEL3_MASK                0x08000000
#define   DTPHY_QSP_ODT_SEL3_SHIFT                       27
#define   DTPHY_QSP_ODT_SEL2_MASK                0x04000000
#define   DTPHY_QSP_ODT_SEL2_SHIFT                       26
#define   DTPHY_QSP_ODT_SEL1_MASK                0x02000000
#define   DTPHY_QSP_ODT_SEL1_SHIFT                       25
#define   DTPHY_QSP_ODT_SEL0_MASK                0x01000000
#define   DTPHY_QSP_ODT_SEL0_SHIFT                       24
#define   DTPHY_QSN_DSTR3_MASK                   0x00008000
#define   DTPHY_QSN_DSTR3_SHIFT                          15
#define   DTPHY_QSN_DSTR2_MASK                   0x00004000
#define   DTPHY_QSN_DSTR2_SHIFT                          14
#define   DTPHY_QSN_DSTR1_MASK                   0x00002000
#define   DTPHY_QSN_DSTR1_SHIFT                          13
#define   DTPHY_QSN_DSTR0_MASK                   0x00001000
#define   DTPHY_QSN_DSTR0_SHIFT                          12
#define   DTPHY_QSN_ODT_SEL3_MASK                0x00000800
#define   DTPHY_QSN_ODT_SEL3_SHIFT                       11
#define   DTPHY_QSN_ODT_SEL2_MASK                0x00000400
#define   DTPHY_QSN_ODT_SEL2_SHIFT                       10
#define   DTPHY_QSN_ODT_SEL1_MASK                0x00000200
#define   DTPHY_QSN_ODT_SEL1_SHIFT                        9
#define   DTPHY_QSN_ODT_SEL0_MASK                0x00000100
#define   DTPHY_QSN_ODT_SEL0_SHIFT                        8

typedef union {
    u32 all;
    struct {
        u32 rsvd_0:8;
        u32 dtphy_qsn_odt_sel0:1;
        u32 dtphy_qsn_odt_sel1:1;
        u32 dtphy_qsn_odt_sel2:1;
        u32 dtphy_qsn_odt_sel3:1;
        u32 dtphy_qsn_dstr0:1;
        u32 dtphy_qsn_dstr1:1;
        u32 dtphy_qsn_dstr2:1;
        u32 dtphy_qsn_dstr3:1;
        u32 rsvd_16:8;
        u32 dtphy_qsp_odt_sel0:1;
        u32 dtphy_qsp_odt_sel1:1;
        u32 dtphy_qsp_odt_sel2:1;
        u32 dtphy_qsp_odt_sel3:1;
        u32 dtphy_qsp_dstr0:1;
        u32 dtphy_qsp_dstr1:1;
        u32 dtphy_qsp_dstr2:1;
        u32 dtphy_qsp_dstr3:1;
    } b;
} dtphy_ctrl_reg14_t;

#define DTPHY_CTRL_REG15                         0x00000044
#define   DTPHY_CLK2X_QSPD_DLY7_MASK             0x80000000
#define   DTPHY_CLK2X_QSPD_DLY7_SHIFT                    31
#define   DTPHY_CLK2X_QSPD_DLY6_MASK             0x40000000
#define   DTPHY_CLK2X_QSPD_DLY6_SHIFT                    30
#define   DTPHY_CLK2X_QSPD_DLY5_MASK             0x20000000
#define   DTPHY_CLK2X_QSPD_DLY5_SHIFT                    29
#define   DTPHY_CLK2X_QSPD_DLY4_MASK             0x10000000
#define   DTPHY_CLK2X_QSPD_DLY4_SHIFT                    28
#define   DTPHY_CLK2X_QSPD_DLY3_MASK             0x08000000
#define   DTPHY_CLK2X_QSPD_DLY3_SHIFT                    27
#define   DTPHY_CLK2X_QSPD_DLY2_MASK             0x04000000
#define   DTPHY_CLK2X_QSPD_DLY2_SHIFT                    26
#define   DTPHY_CLK2X_QSPD_DLY1_MASK             0x02000000
#define   DTPHY_CLK2X_QSPD_DLY1_SHIFT                    25
#define   DTPHY_CLK2X_QSPD_DLY0_MASK             0x01000000
#define   DTPHY_CLK2X_QSPD_DLY0_SHIFT                    24
#define   DTPHY_CLK2X_QSPC_DLY7_MASK             0x00800000
#define   DTPHY_CLK2X_QSPC_DLY7_SHIFT                    23
#define   DTPHY_CLK2X_QSPC_DLY6_MASK             0x00400000
#define   DTPHY_CLK2X_QSPC_DLY6_SHIFT                    22
#define   DTPHY_CLK2X_QSPC_DLY5_MASK             0x00200000
#define   DTPHY_CLK2X_QSPC_DLY5_SHIFT                    21
#define   DTPHY_CLK2X_QSPC_DLY4_MASK             0x00100000
#define   DTPHY_CLK2X_QSPC_DLY4_SHIFT                    20
#define   DTPHY_CLK2X_QSPC_DLY3_MASK             0x00080000
#define   DTPHY_CLK2X_QSPC_DLY3_SHIFT                    19
#define   DTPHY_CLK2X_QSPC_DLY2_MASK             0x00040000
#define   DTPHY_CLK2X_QSPC_DLY2_SHIFT                    18
#define   DTPHY_CLK2X_QSPC_DLY1_MASK             0x00020000
#define   DTPHY_CLK2X_QSPC_DLY1_SHIFT                    17
#define   DTPHY_CLK2X_QSPC_DLY0_MASK             0x00010000
#define   DTPHY_CLK2X_QSPC_DLY0_SHIFT                    16
#define   DTPHY_CLK2X_QSND_DLY7_MASK             0x00008000
#define   DTPHY_CLK2X_QSND_DLY7_SHIFT                    15
#define   DTPHY_CLK2X_QSND_DLY6_MASK             0x00004000
#define   DTPHY_CLK2X_QSND_DLY6_SHIFT                    14
#define   DTPHY_CLK2X_QSND_DLY5_MASK             0x00002000
#define   DTPHY_CLK2X_QSND_DLY5_SHIFT                    13
#define   DTPHY_CLK2X_QSND_DLY4_MASK             0x00001000
#define   DTPHY_CLK2X_QSND_DLY4_SHIFT                    12
#define   DTPHY_CLK2X_QSND_DLY3_MASK             0x00000800
#define   DTPHY_CLK2X_QSND_DLY3_SHIFT                    11
#define   DTPHY_CLK2X_QSND_DLY2_MASK             0x00000400
#define   DTPHY_CLK2X_QSND_DLY2_SHIFT                    10
#define   DTPHY_CLK2X_QSND_DLY1_MASK             0x00000200
#define   DTPHY_CLK2X_QSND_DLY1_SHIFT                     9
#define   DTPHY_CLK2X_QSND_DLY0_MASK             0x00000100
#define   DTPHY_CLK2X_QSND_DLY0_SHIFT                     8
#define   DTPHY_CLK2X_QSNC_DLY7_MASK             0x00000080
#define   DTPHY_CLK2X_QSNC_DLY7_SHIFT                     7
#define   DTPHY_CLK2X_QSNC_DLY6_MASK             0x00000040
#define   DTPHY_CLK2X_QSNC_DLY6_SHIFT                     6
#define   DTPHY_CLK2X_QSNC_DLY5_MASK             0x00000020
#define   DTPHY_CLK2X_QSNC_DLY5_SHIFT                     5
#define   DTPHY_CLK2X_QSNC_DLY4_MASK             0x00000010
#define   DTPHY_CLK2X_QSNC_DLY4_SHIFT                     4
#define   DTPHY_CLK2X_QSNC_DLY3_MASK             0x00000008
#define   DTPHY_CLK2X_QSNC_DLY3_SHIFT                     3
#define   DTPHY_CLK2X_QSNC_DLY2_MASK             0x00000004
#define   DTPHY_CLK2X_QSNC_DLY2_SHIFT                     2
#define   DTPHY_CLK2X_QSNC_DLY1_MASK             0x00000002
#define   DTPHY_CLK2X_QSNC_DLY1_SHIFT                     1
#define   DTPHY_CLK2X_QSNC_DLY0_MASK             0x00000001
#define   DTPHY_CLK2X_QSNC_DLY0_SHIFT                     0

typedef union {
    u32 all;
    struct {
        u32 dtphy_clk2x_qsnc_dly0:1;
        u32 dtphy_clk2x_qsnc_dly1:1;
        u32 dtphy_clk2x_qsnc_dly2:1;
        u32 dtphy_clk2x_qsnc_dly3:1;
        u32 dtphy_clk2x_qsnc_dly4:1;
        u32 dtphy_clk2x_qsnc_dly5:1;
        u32 dtphy_clk2x_qsnc_dly6:1;
        u32 dtphy_clk2x_qsnc_dly7:1;
        u32 dtphy_clk2x_qsnd_dly0:1;
        u32 dtphy_clk2x_qsnd_dly1:1;
        u32 dtphy_clk2x_qsnd_dly2:1;
        u32 dtphy_clk2x_qsnd_dly3:1;
        u32 dtphy_clk2x_qsnd_dly4:1;
        u32 dtphy_clk2x_qsnd_dly5:1;
        u32 dtphy_clk2x_qsnd_dly6:1;
        u32 dtphy_clk2x_qsnd_dly7:1;
        u32 dtphy_clk2x_qspc_dly0:1;
        u32 dtphy_clk2x_qspc_dly1:1;
        u32 dtphy_clk2x_qspc_dly2:1;
        u32 dtphy_clk2x_qspc_dly3:1;
        u32 dtphy_clk2x_qspc_dly4:1;
        u32 dtphy_clk2x_qspc_dly5:1;
        u32 dtphy_clk2x_qspc_dly6:1;
        u32 dtphy_clk2x_qspc_dly7:1;
        u32 dtphy_clk2x_qspd_dly0:1;
        u32 dtphy_clk2x_qspd_dly1:1;
        u32 dtphy_clk2x_qspd_dly2:1;
        u32 dtphy_clk2x_qspd_dly3:1;
        u32 dtphy_clk2x_qspd_dly4:1;
        u32 dtphy_clk2x_qspd_dly5:1;
        u32 dtphy_clk2x_qspd_dly6:1;
        u32 dtphy_clk2x_qspd_dly7:1;
    } b;
} dtphy_ctrl_reg15_t;

#define DTPHY_CTRL_REG16                         0x00000048
#define   DTPHY_QSP_OE_REG_MASK                  0x80000000
#define   DTPHY_QSP_OE_REG_SHIFT                         31
#define   DTPHY_QSN_OE_REG_MASK                  0x40000000
#define   DTPHY_QSN_OE_REG_SHIFT                         30
#define   DTPHY_DQ_OE_REG_MASK                   0x20000000
#define   DTPHY_DQ_OE_REG_SHIFT                          29
#define   DTPHY_QSP_REG_OE0_MASK                 0x00080000
#define   DTPHY_QSP_REG_OE0_SHIFT                        19
#define   DTPHY_QSP_REG_OE1_MASK                 0x00040000
#define   DTPHY_QSP_REG_OE1_SHIFT                        18
#define   DTPHY_QSN_REG_OE0_MASK                 0x00020000
#define   DTPHY_QSN_REG_OE0_SHIFT                        17
#define   DTPHY_QSN_REG_OE1_MASK                 0x00010000
#define   DTPHY_QSN_REG_OE1_SHIFT                        16
#define   DTPHY_DQ_REG_OE0_MASK                  0x0000ff00
#define   DTPHY_DQ_REG_OE0_SHIFT                          8
#define   DTPHY_DQ_REG_OE1_MASK                  0x000000ff
#define   DTPHY_DQ_REG_OE1_SHIFT                          0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dq_reg_oe1:8;
        u32 dtphy_dq_reg_oe0:8;
        u32 dtphy_qsn_reg_oe1:1;
        u32 dtphy_qsn_reg_oe0:1;
        u32 dtphy_qsp_reg_oe1:1;
        u32 dtphy_qsp_reg_oe0:1;
        u32 rsvd_20:9;
        u32 dtphy_dq_oe_reg:1;
        u32 dtphy_qsn_oe_reg:1;
        u32 dtphy_qsp_oe_reg:1;
    } b;
} dtphy_ctrl_reg16_t;

#define DTPHY_CTRL_REG17                         0x0000004c
#define   DTPHY_QSP_RCVR_REG_MASK                0x80000000
#define   DTPHY_QSP_RCVR_REG_SHIFT                       31
#define   DTPHY_QSN_RCVR_REG_MASK                0x40000000
#define   DTPHY_QSN_RCVR_REG_SHIFT                       30
#define   DTPHY_DQ_RCVR_REG_MASK                 0x20000000
#define   DTPHY_DQ_RCVR_REG_SHIFT                        29
#define   DTPHY_QSP_REG_RECEN_MASK               0x00000200
#define   DTPHY_QSP_REG_RECEN_SHIFT                       9
#define   DTPHY_QSN_REG_RECEN_MASK               0x00000100
#define   DTPHY_QSN_REG_RECEN_SHIFT                       8
#define   DTPHY_DQ_REG_RECEN_MASK                0x000000ff
#define   DTPHY_DQ_REG_RECEN_SHIFT                        0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dq_reg_recen:8;
        u32 dtphy_qsn_reg_recen:1;
        u32 dtphy_qsp_reg_recen:1;
        u32 rsvd_10:19;
        u32 dtphy_dq_rcvr_reg:1;
        u32 dtphy_qsn_rcvr_reg:1;
        u32 dtphy_qsp_rcvr_reg:1;
    } b;
} dtphy_ctrl_reg17_t;

#define DTPHY_DLL_CFG_PTR                        0x00000050
#define   DTPHY_DLL_CFG_PTR_MASK                 0x000000ff
#define   DTPHY_DLL_CFG_PTR_SHIFT                         0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dll_cfg_ptr:8;
        u32 rsvd_8:24;
    } b;
} dtphy_dll_cfg_ptr_t;

#define DTPHY_DLL_PHASE                          0x00000054
#define   DTPHY_DLL_PHASE_MASK                   0x00000fff
#define   DTPHY_DLL_PHASE_SHIFT                           0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dll_phase:12;
        u32 rsvd_12:20;
    } b;
} dtphy_dll_phase_t;

#define DTPHY_DLL_DQ_DLY                         0x00000058
#define   DTPHY_DLL_DQ_DLY_MASK                  0x00ffffff
#define   DTPHY_DLL_DQ_DLY_SHIFT                          0

typedef union {
    u32 all;
    struct {
        u32 dtphy_dll_dq_dly:24;
        u32 rsvd_24:8;
    } b;
} dtphy_dll_dq_dly_t;

#define ND_PHY_CALIB_REG0                        0x00000060
#define   ND_CAL_ZQ_DONE_MASK                    0x00000040
#define   ND_CAL_ZQ_DONE_SHIFT                            6
#define   ND_CAL_ZQ_TRIM_MASK                    0x00000030
#define   ND_CAL_ZQ_TRIM_SHIFT                            4
#define   ND_CAL_VOL_SEL_MASK                    0x00000008
#define   ND_CAL_VOL_SEL_SHIFT                            3
#define   ND_CAL_ZQ_EN_MASK                      0x00000004
#define   ND_CAL_ZQ_EN_SHIFT                              2
#define   ND_CAL_TEST_MASK                       0x00000003
#define   ND_CAL_TEST_SHIFT                               0

typedef union {
    u32 all;
    struct {
        u32 nd_cal_test:2;
        u32 nd_cal_zq_en:1;
        u32 nd_cal_vol_sel:1;
        u32 nd_cal_zq_trim:2;
        u32 nd_cal_zq_done:1;
        u32 rsvd_7:25;
    } b;
} nd_phy_calib_reg0_t;

#define CMDPHY_WP_CTRL_REG                       0x00000080
#define   CMDPHY_DIFF_FORCE_VAL_MASK             0x00006000
#define   CMDPHY_DIFF_FORCE_VAL_SHIFT                    13
#define   CMDPHY_DIFF_EN_MASK                    0x00001000
#define   CMDPHY_DIFF_EN_SHIFT                           12
#define   CMDPHY_WP_VAL_MASK                     0x00000800
#define   CMDPHY_WP_VAL_SHIFT                            11
#define   CMDPHY_WP_CTRL_MASK                    0x00000400
#define   CMDPHY_WP_CTRL_SHIFT                           10

typedef union {
    u32 all;
    struct {
        u32 rsvd_0:10;
        u32 cmdphy_wp_ctrl:1;
        u32 cmdphy_wp_val:1;
        u32 cmdphy_diff_en:1;
        u32 cmdphy_diff_force_val:2;
        u32 rsvd_15:17;
    } b;
} cmdphy_wp_ctrl_reg_t;

#define CMDPHY_CTRL_REG0                         0x00000088
#define   CMDPHY_TDIE_MASK                       0xff000000
#define   CMDPHY_TDIE_SHIFT                              24
#define   CMDPHY_LPBK_DLY_MASK                   0x00f00000
#define   CMDPHY_LPBK_DLY_SHIFT                          20
#define   CMDPHY_TDOE_MASK                       0x00040000
#define   CMDPHY_TDOE_SHIFT                              18
#define   CMDPHY_TMS_MASK                        0x00020000
#define   CMDPHY_TMS_SHIFT                               17
#define   CMDPHY_ASYNC_MODE_MASK                 0x00010000
#define   CMDPHY_ASYNC_MODE_SHIFT                        16
#define   CMDPHY_QS_GATE_DLY_SEL_MASK            0x0000ff00
#define   CMDPHY_QS_GATE_DLY_SEL_SHIFT                    8
#define   CMDPHY_ASYNC_DLY_SEL_MASK              0x000000ff
#define   CMDPHY_ASYNC_DLY_SEL_SHIFT                      0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_async_dly_sel:8;
        u32 cmdphy_qs_gate_dly_sel:8;
        u32 cmdphy_async_mode:1;
        u32 cmdphy_tms:1;
        u32 cmdphy_tdoe:1;
        u32 rsvd_19:1;
        u32 cmdphy_lpbk_dly:4;
        u32 cmdphy_tdie:8;
    } b;
} cmdphy_ctrl_reg0_t;

#define CMDPHY_CTRL_REG1                         0x0000008c
#define   CMDPHY_LPBK_RDPTR_DLY_MASK             0x07000000
#define   CMDPHY_LPBK_RDPTR_DLY_SHIFT                    24
#define   PWRDWN_8c_MASK                         0x00ff0000
#define   PWRDWN_8c_SHIFT                                16
#define   CMDPHY_NVDDR_MASK                      0x0000ff00
#define   CMDPHY_NVDDR_SHIFT                              8
#define   CMDPHY_DQ_RCVTYPE_MASK                 0x000000ff
#define   CMDPHY_DQ_RCVTYPE_SHIFT                         0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dq_rcvtype:8;
        u32 cmdphy_nvddr:8;
        u32 pwrdwn_8c:8;
        u32 cmdphy_lpbk_rdptr_dly:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg1_t;

#define CMDPHY_CTRL_REG2                         0x00000090
#define   CMDPHY_PU_MASK                         0xff000000
#define   CMDPHY_PU_SHIFT                                24
#define   CMDPHY_PD_MASK                         0x00ff0000
#define   CMDPHY_PD_SHIFT                                16
#define   CMDPHY_DQ_SLR_MASK                     0x0000ff00
#define   CMDPHY_DQ_SLR_SHIFT                             8
#define   CMDPHY_DQ_MS_MASK                      0x000000ff
#define   CMDPHY_DQ_MS_SHIFT                              0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dq_ms:8;
        u32 cmdphy_dq_slr:8;
        u32 cmdphy_pd:8;
        u32 cmdphy_pu:8;
    } b;
} cmdphy_ctrl_reg2_t;

#define CMDPHY_CTRL_REG3                         0x00000094
#define   CMDPHY_DLL_PHSEL1_MASK                 0x0fc00000
#define   CMDPHY_DLL_PHSEL1_SHIFT                        22
#define   CMDPHY_DLL_LOCKED_MASK                 0x00200000
#define   CMDPHY_DLL_LOCKED_SHIFT                        21
#define   CMDPHY_DLL_UPDATE_EN_MASK              0x00100000
#define   CMDPHY_DLL_UPDATE_EN_SHIFT                     20
#define   CMDPHY_DLL_RSTB_MASK                   0x00020000
#define   CMDPHY_DLL_RSTB_SHIFT                          17
#define   CMDPHY_DLL_TEST_EN_MASK                0x00010000
#define   CMDPHY_DLL_TEST_EN_SHIFT                       16
#define   CMDPHY_DLL_PHSEL0_MASK                 0x0000fc00
#define   CMDPHY_DLL_PHSEL0_SHIFT                        10
#define   CMDPHY_DLL_BYPASS_EN_MASK              0x00000200
#define   CMDPHY_DLL_BYPASS_EN_SHIFT                      9
#define   CMDPHY_DLL_DLY_TEST_MASK               0x000001ff
#define   CMDPHY_DLL_DLY_TEST_SHIFT                       0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dll_dly_test:9;
        u32 cmdphy_dll_bypass_en:1;
        u32 cmdphy_dll_phsel0:6;
        u32 cmdphy_dll_test_en:1;
        u32 cmdphy_dll_rstb:1;
        u32 rsvd_18:2;
        u32 cmdphy_dll_update_en:1;
        u32 cmdphy_dll_locked:1;
        u32 cmdphy_dll_phsel1:6;
        u32 rsvd_28:4;
    } b;
} cmdphy_ctrl_reg3_t;

#define CMDPHY_CTRL_REG4                         0x00000098
#define   CMDPHY_FC_ODT_EN_MASK                  0x00000020
#define   CMDPHY_FC_ODT_EN_SHIFT                          5
#define   CMDPHY_FC_PSTR_MASK                    0x0000001f
#define   CMDPHY_FC_PSTR_SHIFT                            0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_fc_pstr:5;
        u32 cmdphy_fc_odt_en:1;
        u32 rsvd_6:26;
    } b;
} cmdphy_ctrl_reg4_t;

#define CMDPHY_CTRL_REG5                         0x0000009c
#define   CMDPHY_DSTR3_MASK                      0xff000000
#define   CMDPHY_DSTR3_SHIFT                             24
#define   CMDPHY_DSTR2_MASK                      0x00ff0000
#define   CMDPHY_DSTR2_SHIFT                             16
#define   CMDPHY_DSTR1_MASK                      0x0000ff00
#define   CMDPHY_DSTR1_SHIFT                              8
#define   CMDPHY_DSTR0_MASK                      0x000000ff
#define   CMDPHY_DSTR0_SHIFT                              0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dstr0:8;
        u32 cmdphy_dstr1:8;
        u32 cmdphy_dstr2:8;
        u32 cmdphy_dstr3:8;
    } b;
} cmdphy_ctrl_reg5_t;

#define CMDPHY_CTRL_REG6                         0x000000a0
#define   CMDPHY_ODT_SEL3_MASK                   0xff000000
#define   CMDPHY_ODT_SEL3_SHIFT                          24
#define   CMDPHY_ODT_SEL2_MASK                   0x00ff0000
#define   CMDPHY_ODT_SEL2_SHIFT                          16
#define   CMDPHY_ODT_SEL1_MASK                   0x0000ff00
#define   CMDPHY_ODT_SEL1_SHIFT                           8
#define   CMDPHY_ODT_SEL0_MASK                   0x000000ff
#define   CMDPHY_ODT_SEL0_SHIFT                           0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_odt_sel0:8;
        u32 cmdphy_odt_sel1:8;
        u32 cmdphy_odt_sel2:8;
        u32 cmdphy_odt_sel3:8;
    } b;
} cmdphy_ctrl_reg6_t;

#define CMDPHY_CTRL_REG7                         0x000000a4
#define   CMDPHY_CTRL_REG7_RSVVD_MASK            0xffffffff
#define   CMDPHY_CTRL_REG7_RSVVD_SHIFT                    0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_ctrl_reg7_rsvvd:32;
    } b;
} cmdphy_ctrl_reg7_t;

#define CMDPHY_CTRL_REG8                         0x000000a8
#define   CMDPHY_CTRL_REG8_RSVVD_MASK            0xffffffff
#define   CMDPHY_CTRL_REG8_RSVVD_SHIFT                    0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_ctrl_reg8_rsvvd:32;
    } b;
} cmdphy_ctrl_reg8_t;

#define CMDPHY_CTRL_REG9                         0x000000ac
#define   CMDPHY_CLK2X_DQD_DLY7_MASK             0xff000000
#define   CMDPHY_CLK2X_DQD_DLY7_SHIFT                    24
#define   CMDPHY_CLK2X_DQD_DLY6_MASK             0x00ff0000
#define   CMDPHY_CLK2X_DQD_DLY6_SHIFT                    16
#define   CMDPHY_CLK2X_DQD_DLY5_MASK             0x0000ff00
#define   CMDPHY_CLK2X_DQD_DLY5_SHIFT                     8
#define   CMDPHY_CLK2X_DQD_DLY4_MASK             0x000000ff
#define   CMDPHY_CLK2X_DQD_DLY4_SHIFT                     0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_dqd_dly4:8;
        u32 cmdphy_clk2x_dqd_dly5:8;
        u32 cmdphy_clk2x_dqd_dly6:8;
        u32 cmdphy_clk2x_dqd_dly7:8;
    } b;
} cmdphy_ctrl_reg9_t;

#define CMDPHY_CTRL_REG10                        0x000000b0
#define   CMDPHY_CLK2X_DQD_DLY3_MASK             0xff000000
#define   CMDPHY_CLK2X_DQD_DLY3_SHIFT                    24
#define   CMDPHY_CLK2X_DQD_DLY2_MASK             0x00ff0000
#define   CMDPHY_CLK2X_DQD_DLY2_SHIFT                    16
#define   CMDPHY_CLK2X_DQD_DLY1_MASK             0x0000ff00
#define   CMDPHY_CLK2X_DQD_DLY1_SHIFT                     8
#define   CMDPHY_CLK2X_DQD_DLY0_MASK             0x000000ff
#define   CMDPHY_CLK2X_DQD_DLY0_SHIFT                     0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_dqd_dly0:8;
        u32 cmdphy_clk2x_dqd_dly1:8;
        u32 cmdphy_clk2x_dqd_dly2:8;
        u32 cmdphy_clk2x_dqd_dly3:8;
    } b;
} cmdphy_ctrl_reg10_t;

#define CMDPHY_CTRL_REG11                        0x000000b4
#define   CMDPHY_CLK2X_DQC_DLY7_MASK             0xff000000
#define   CMDPHY_CLK2X_DQC_DLY7_SHIFT                    24
#define   CMDPHY_CLK2X_DQC_DLY6_MASK             0x00ff0000
#define   CMDPHY_CLK2X_DQC_DLY6_SHIFT                    16
#define   CMDPHY_CLK2X_DQC_DLY5_MASK             0x0000ff00
#define   CMDPHY_CLK2X_DQC_DLY5_SHIFT                     8
#define   CMDPHY_CLK2X_DQC_DLY4_MASK             0x000000ff
#define   CMDPHY_CLK2X_DQC_DLY4_SHIFT                     0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_dqc_dly4:8;
        u32 cmdphy_clk2x_dqc_dly5:8;
        u32 cmdphy_clk2x_dqc_dly6:8;
        u32 cmdphy_clk2x_dqc_dly7:8;
    } b;
} cmdphy_ctrl_reg11_t;

#define CMDPHY_CTRL_REG12                        0x000000b8
#define   CMDPHY_CLK2X_DQC_DLY3_MASK             0xff000000
#define   CMDPHY_CLK2X_DQC_DLY3_SHIFT                    24
#define   CMDPHY_CLK2X_DQC_DLY2_MASK             0x00ff0000
#define   CMDPHY_CLK2X_DQC_DLY2_SHIFT                    16
#define   CMDPHY_CLK2X_DQC_DLY1_MASK             0x0000ff00
#define   CMDPHY_CLK2X_DQC_DLY1_SHIFT                     8
#define   CMDPHY_CLK2X_DQC_DLY0_MASK             0x000000ff
#define   CMDPHY_CLK2X_DQC_DLY0_SHIFT                     0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_dqc_dly0:8;
        u32 cmdphy_clk2x_dqc_dly1:8;
        u32 cmdphy_clk2x_dqc_dly2:8;
        u32 cmdphy_clk2x_dqc_dly3:8;
    } b;
} cmdphy_ctrl_reg12_t;

#define CMDPHY_CTRL_REG13                        0x000000bc
#define   CMDPHY_QSP_TDIE_MASK                   0x00008000
#define   CMDPHY_QSP_TDIE_SHIFT                          15
#define   CMDPHY_QSP_PU_MASK                     0x00004000
#define   CMDPHY_QSP_PU_SHIFT                            14
#define   CMDPHY_QSP_PD_MASK                     0x00002000
#define   CMDPHY_QSP_PD_SHIFT                            13
#define   CMDPHY_QSP_RCVTYPE_MASK                0x00001000
#define   CMDPHY_QSP_RCVTYPE_SHIFT                       12
#define   CMDPHY_QSP_SLR_MASK                    0x00000800
#define   CMDPHY_QSP_SLR_SHIFT                           11
#define   CMDPHY_QSP_MS_MASK                     0x00000400
#define   CMDPHY_QSP_MS_SHIFT                            10
#define   CMDPHY_QSP_PWRDWN_MASK                 0x00000200
#define   CMDPHY_QSP_PWRDWN_SHIFT                         9
#define   CMDPHY_QSP_NVDDR_MASK                  0x00000100
#define   CMDPHY_QSP_NVDDR_SHIFT                          8
#define   CMDPHY_QSN_TDIE_MASK                   0x00000080
#define   CMDPHY_QSN_TDIE_SHIFT                           7
#define   CMDPHY_QSN_PU_MASK                     0x00000040
#define   CMDPHY_QSN_PU_SHIFT                             6
#define   CMDPHY_QSN_PD_MASK                     0x00000020
#define   CMDPHY_QSN_PD_SHIFT                             5
#define   CMDPHY_QSN_RCVTYPE_MASK                0x00000010
#define   CMDPHY_QSN_RCVTYPE_SHIFT                        4
#define   CMDPHY_QSN_SLR_MASK                    0x00000008
#define   CMDPHY_QSN_SLR_SHIFT                            3
#define   CMDPHY_QSN_MS_MASK                     0x00000004
#define   CMDPHY_QSN_MS_SHIFT                             2
#define   CMDPHY_QSN_PWRDWN_MASK                 0x00000002
#define   CMDPHY_QSN_PWRDWN_SHIFT                         1
#define   CMDPHY_QSN_NVDDR_MASK                  0x00000001
#define   CMDPHY_QSN_NVDDR_SHIFT                          0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_qsn_nvddr:1;
        u32 cmdphy_qsn_pwrdwn:1;
        u32 cmdphy_qsn_ms:1;
        u32 cmdphy_qsn_slr:1;
        u32 cmdphy_qsn_rcvtype:1;
        u32 cmdphy_qsn_pd:1;
        u32 cmdphy_qsn_pu:1;
        u32 cmdphy_qsn_tdie:1;
        u32 cmdphy_qsp_nvddr:1;
        u32 cmdphy_qsp_pwrdwn:1;
        u32 cmdphy_qsp_ms:1;
        u32 cmdphy_qsp_slr:1;
        u32 cmdphy_qsp_rcvtype:1;
        u32 cmdphy_qsp_pd:1;
        u32 cmdphy_qsp_pu:1;
        u32 cmdphy_qsp_tdie:1;
        u32 rsvd_16:16;
    } b;
} cmdphy_ctrl_reg13_t;

#define CMDPHY_CTRL_REG14                        0x000000c0
#define   CMDPHY_QSP_DSTR3_MASK                  0x80000000
#define   CMDPHY_QSP_DSTR3_SHIFT                         31
#define   CMDPHY_QSP_DSTR2_MASK                  0x40000000
#define   CMDPHY_QSP_DSTR2_SHIFT                         30
#define   CMDPHY_QSP_DSTR1_MASK                  0x20000000
#define   CMDPHY_QSP_DSTR1_SHIFT                         29
#define   CMDPHY_QSP_DSTR0_MASK                  0x10000000
#define   CMDPHY_QSP_DSTR0_SHIFT                         28
#define   CMDPHY_QSP_ODT_SEL3_MASK               0x08000000
#define   CMDPHY_QSP_ODT_SEL3_SHIFT                      27
#define   CMDPHY_QSP_ODT_SEL2_MASK               0x04000000
#define   CMDPHY_QSP_ODT_SEL2_SHIFT                      26
#define   CMDPHY_QSP_ODT_SEL1_MASK               0x02000000
#define   CMDPHY_QSP_ODT_SEL1_SHIFT                      25
#define   CMDPHY_QSP_ODT_SEL0_MASK               0x01000000
#define   CMDPHY_QSP_ODT_SEL0_SHIFT                      24
#define   CMDPHY_QSN_DSTR3_MASK                  0x00008000
#define   CMDPHY_QSN_DSTR3_SHIFT                         15
#define   CMDPHY_QSN_DSTR2_MASK                  0x00004000
#define   CMDPHY_QSN_DSTR2_SHIFT                         14
#define   CMDPHY_QSN_DSTR1_MASK                  0x00002000
#define   CMDPHY_QSN_DSTR1_SHIFT                         13
#define   CMDPHY_QSN_DSTR0_MASK                  0x00001000
#define   CMDPHY_QSN_DSTR0_SHIFT                         12
#define   CMDPHY_QSN_ODT_SEL3_MASK               0x00000800
#define   CMDPHY_QSN_ODT_SEL3_SHIFT                      11
#define   CMDPHY_QSN_ODT_SEL2_MASK               0x00000400
#define   CMDPHY_QSN_ODT_SEL2_SHIFT                      10
#define   CMDPHY_QSN_ODT_SEL1_MASK               0x00000200
#define   CMDPHY_QSN_ODT_SEL1_SHIFT                       9
#define   CMDPHY_QSN_ODT_SEL0_MASK               0x00000100
#define   CMDPHY_QSN_ODT_SEL0_SHIFT                       8

typedef union {
    u32 all;
    struct {
        u32 rsvd_0:8;
        u32 cmdphy_qsn_odt_sel0:1;
        u32 cmdphy_qsn_odt_sel1:1;
        u32 cmdphy_qsn_odt_sel2:1;
        u32 cmdphy_qsn_odt_sel3:1;
        u32 cmdphy_qsn_dstr0:1;
        u32 cmdphy_qsn_dstr1:1;
        u32 cmdphy_qsn_dstr2:1;
        u32 cmdphy_qsn_dstr3:1;
        u32 rsvd_16:8;
        u32 cmdphy_qsp_odt_sel0:1;
        u32 cmdphy_qsp_odt_sel1:1;
        u32 cmdphy_qsp_odt_sel2:1;
        u32 cmdphy_qsp_odt_sel3:1;
        u32 cmdphy_qsp_dstr0:1;
        u32 cmdphy_qsp_dstr1:1;
        u32 cmdphy_qsp_dstr2:1;
        u32 cmdphy_qsp_dstr3:1;
    } b;
} cmdphy_ctrl_reg14_t;

#define CMDPHY_CTRL_REG15                        0x000000c4
#define   CMDPHY_CLK2X_QSPD_DLY7_MASK            0x80000000
#define   CMDPHY_CLK2X_QSPD_DLY7_SHIFT                   31
#define   CMDPHY_CLK2X_QSPD_DLY6_MASK            0x40000000
#define   CMDPHY_CLK2X_QSPD_DLY6_SHIFT                   30
#define   CMDPHY_CLK2X_QSPD_DLY5_MASK            0x20000000
#define   CMDPHY_CLK2X_QSPD_DLY5_SHIFT                   29
#define   CMDPHY_CLK2X_QSPD_DLY4_MASK            0x10000000
#define   CMDPHY_CLK2X_QSPD_DLY4_SHIFT                   28
#define   CMDPHY_CLK2X_QSPD_DLY3_MASK            0x08000000
#define   CMDPHY_CLK2X_QSPD_DLY3_SHIFT                   27
#define   CMDPHY_CLK2X_QSPD_DLY2_MASK            0x04000000
#define   CMDPHY_CLK2X_QSPD_DLY2_SHIFT                   26
#define   CMDPHY_CLK2X_QSPD_DLY1_MASK            0x02000000
#define   CMDPHY_CLK2X_QSPD_DLY1_SHIFT                   25
#define   CMDPHY_CLK2X_QSPD_DLY0_MASK            0x01000000
#define   CMDPHY_CLK2X_QSPD_DLY0_SHIFT                   24
#define   CMDPHY_CLK2X_QSPC_DLY7_MASK            0x00800000
#define   CMDPHY_CLK2X_QSPC_DLY7_SHIFT                   23
#define   CMDPHY_CLK2X_QSPC_DLY6_MASK            0x00400000
#define   CMDPHY_CLK2X_QSPC_DLY6_SHIFT                   22
#define   CMDPHY_CLK2X_QSPC_DLY5_MASK            0x00200000
#define   CMDPHY_CLK2X_QSPC_DLY5_SHIFT                   21
#define   CMDPHY_CLK2X_QSPC_DLY4_MASK            0x00100000
#define   CMDPHY_CLK2X_QSPC_DLY4_SHIFT                   20
#define   CMDPHY_CLK2X_QSPC_DLY3_MASK            0x00080000
#define   CMDPHY_CLK2X_QSPC_DLY3_SHIFT                   19
#define   CMDPHY_CLK2X_QSPC_DLY2_MASK            0x00040000
#define   CMDPHY_CLK2X_QSPC_DLY2_SHIFT                   18
#define   CMDPHY_CLK2X_QSPC_DLY1_MASK            0x00020000
#define   CMDPHY_CLK2X_QSPC_DLY1_SHIFT                   17
#define   CMDPHY_CLK2X_QSPC_DLY0_MASK            0x00010000
#define   CMDPHY_CLK2X_QSPC_DLY0_SHIFT                   16
#define   CMDPHY_CLK2X_QSND_DLY7_MASK            0x00008000
#define   CMDPHY_CLK2X_QSND_DLY7_SHIFT                   15
#define   CMDPHY_CLK2X_QSND_DLY6_MASK            0x00004000
#define   CMDPHY_CLK2X_QSND_DLY6_SHIFT                   14
#define   CMDPHY_CLK2X_QSND_DLY5_MASK            0x00002000
#define   CMDPHY_CLK2X_QSND_DLY5_SHIFT                   13
#define   CMDPHY_CLK2X_QSND_DLY4_MASK            0x00001000
#define   CMDPHY_CLK2X_QSND_DLY4_SHIFT                   12
#define   CMDPHY_CLK2X_QSND_DLY3_MASK            0x00000800
#define   CMDPHY_CLK2X_QSND_DLY3_SHIFT                   11
#define   CMDPHY_CLK2X_QSND_DLY2_MASK            0x00000400
#define   CMDPHY_CLK2X_QSND_DLY2_SHIFT                   10
#define   CMDPHY_CLK2X_QSND_DLY1_MASK            0x00000200
#define   CMDPHY_CLK2X_QSND_DLY1_SHIFT                    9
#define   CMDPHY_CLK2X_QSND_DLY0_MASK            0x00000100
#define   CMDPHY_CLK2X_QSND_DLY0_SHIFT                    8
#define   CMDPHY_CLK2X_QSNC_DLY7_MASK            0x00000080
#define   CMDPHY_CLK2X_QSNC_DLY7_SHIFT                    7
#define   CMDPHY_CLK2X_QSNC_DLY6_MASK            0x00000040
#define   CMDPHY_CLK2X_QSNC_DLY6_SHIFT                    6
#define   CMDPHY_CLK2X_QSNC_DLY5_MASK            0x00000020
#define   CMDPHY_CLK2X_QSNC_DLY5_SHIFT                    5
#define   CMDPHY_CLK2X_QSNC_DLY4_MASK            0x00000010
#define   CMDPHY_CLK2X_QSNC_DLY4_SHIFT                    4
#define   CMDPHY_CLK2X_QSNC_DLY3_MASK            0x00000008
#define   CMDPHY_CLK2X_QSNC_DLY3_SHIFT                    3
#define   CMDPHY_CLK2X_QSNC_DLY2_MASK            0x00000004
#define   CMDPHY_CLK2X_QSNC_DLY2_SHIFT                    2
#define   CMDPHY_CLK2X_QSNC_DLY1_MASK            0x00000002
#define   CMDPHY_CLK2X_QSNC_DLY1_SHIFT                    1
#define   CMDPHY_CLK2X_QSNC_DLY0_MASK            0x00000001
#define   CMDPHY_CLK2X_QSNC_DLY0_SHIFT                    0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_qsnc_dly0:1;
        u32 cmdphy_clk2x_qsnc_dly1:1;
        u32 cmdphy_clk2x_qsnc_dly2:1;
        u32 cmdphy_clk2x_qsnc_dly3:1;
        u32 cmdphy_clk2x_qsnc_dly4:1;
        u32 cmdphy_clk2x_qsnc_dly5:1;
        u32 cmdphy_clk2x_qsnc_dly6:1;
        u32 cmdphy_clk2x_qsnc_dly7:1;
        u32 cmdphy_clk2x_qsnd_dly0:1;
        u32 cmdphy_clk2x_qsnd_dly1:1;
        u32 cmdphy_clk2x_qsnd_dly2:1;
        u32 cmdphy_clk2x_qsnd_dly3:1;
        u32 cmdphy_clk2x_qsnd_dly4:1;
        u32 cmdphy_clk2x_qsnd_dly5:1;
        u32 cmdphy_clk2x_qsnd_dly6:1;
        u32 cmdphy_clk2x_qsnd_dly7:1;
        u32 cmdphy_clk2x_qspc_dly0:1;
        u32 cmdphy_clk2x_qspc_dly1:1;
        u32 cmdphy_clk2x_qspc_dly2:1;
        u32 cmdphy_clk2x_qspc_dly3:1;
        u32 cmdphy_clk2x_qspc_dly4:1;
        u32 cmdphy_clk2x_qspc_dly5:1;
        u32 cmdphy_clk2x_qspc_dly6:1;
        u32 cmdphy_clk2x_qspc_dly7:1;
        u32 cmdphy_clk2x_qspd_dly0:1;
        u32 cmdphy_clk2x_qspd_dly1:1;
        u32 cmdphy_clk2x_qspd_dly2:1;
        u32 cmdphy_clk2x_qspd_dly3:1;
        u32 cmdphy_clk2x_qspd_dly4:1;
        u32 cmdphy_clk2x_qspd_dly5:1;
        u32 cmdphy_clk2x_qspd_dly6:1;
        u32 cmdphy_clk2x_qspd_dly7:1;
    } b;
} cmdphy_ctrl_reg15_t;

#define CMDPHY_CTRL_REG16                        0x000000c8
#define   CMDPHY_QSP_OE_REG_MASK                 0x80000000
#define   CMDPHY_QSP_OE_REG_SHIFT                        31
#define   CMDPHY_QSN_OE_REG_MASK                 0x40000000
#define   CMDPHY_QSN_OE_REG_SHIFT                        30
#define   CMDPHY_DQ_OE_REG_MASK                  0x20000000
#define   CMDPHY_DQ_OE_REG_SHIFT                         29
#define   CMDPHY_QSP_REG_OE0_MASK                0x00080000
#define   CMDPHY_QSP_REG_OE0_SHIFT                       19
#define   CMDPHY_QSP_REG_OE1_MASK                0x00040000
#define   CMDPHY_QSP_REG_OE1_SHIFT                       18
#define   CMDPHY_QSN_REG_OE0_MASK                0x00020000
#define   CMDPHY_QSN_REG_OE0_SHIFT                       17
#define   CMDPHY_QSN_REG_OE1_MASK                0x00010000
#define   CMDPHY_QSN_REG_OE1_SHIFT                       16
#define   CMDPHY_DQ_REG_OE0_MASK                 0x0000ff00
#define   CMDPHY_DQ_REG_OE0_SHIFT                         8
#define   CMDPHY_DQ_REG_OE1_MASK                 0x000000ff
#define   CMDPHY_DQ_REG_OE1_SHIFT                         0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dq_reg_oe1:8;
        u32 cmdphy_dq_reg_oe0:8;
        u32 cmdphy_qsn_reg_oe1:1;
        u32 cmdphy_qsn_reg_oe0:1;
        u32 cmdphy_qsp_reg_oe1:1;
        u32 cmdphy_qsp_reg_oe0:1;
        u32 rsvd_20:9;
        u32 cmdphy_dq_oe_reg:1;
        u32 cmdphy_qsn_oe_reg:1;
        u32 cmdphy_qsp_oe_reg:1;
    } b;
} cmdphy_ctrl_reg16_t;

#define CMDPHY_CTRL_REG17                        0x000000cc
#define   CMDPHY_QSP_RCVR_REG_MASK               0x80000000
#define   CMDPHY_QSP_RCVR_REG_SHIFT                      31
#define   CMDPHY_QSN_RCVR_REG_MASK               0x40000000
#define   CMDPHY_QSN_RCVR_REG_SHIFT                      30
#define   CMDPHY_DQ_RCVR_REG_MASK                0x20000000
#define   CMDPHY_DQ_RCVR_REG_SHIFT                       29
#define   CMDPHY_QSP_REG_RECEN_MASK              0x00000200
#define   CMDPHY_QSP_REG_RECEN_SHIFT                      9
#define   CMDPHY_QSN_REG_RECEN_MASK              0x00000100
#define   CMDPHY_QSN_REG_RECEN_SHIFT                      8
#define   CMDPHY_DQ_REG_RECEN_MASK               0x000000ff
#define   CMDPHY_DQ_REG_RECEN_SHIFT                       0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dq_reg_recen:8;
        u32 cmdphy_qsn_reg_recen:1;
        u32 cmdphy_qsp_reg_recen:1;
        u32 rsvd_10:19;
        u32 cmdphy_dq_rcvr_reg:1;
        u32 cmdphy_qsn_rcvr_reg:1;
        u32 cmdphy_qsp_rcvr_reg:1;
    } b;
} cmdphy_ctrl_reg17_t;

#define CMDPHY_CTRL_REG18                        0x000000d0
#define   CMDPHY_TDIE_d0_MASK                    0x07000000
#define   CMDPHY_TDIE_d0_SHIFT                           24
#define   PWRDWN_d0_MASK                         0x00070000
#define   PWRDWN_d0_SHIFT                                16
#define   CMDPHY_NVDDR_d0_MASK                   0x00000700
#define   CMDPHY_NVDDR_d0_SHIFT                           8
#define   CMDPHY_DQ_RCVTYPE_d0_MASK              0x00000007
#define   CMDPHY_DQ_RCVTYPE_d0_SHIFT                      0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dq_rcvtype_d0:3;
        u32 rsvd_3:5;
        u32 cmdphy_nvddr_d0:3;
        u32 rsvd_11:5;
        u32 pwrdwn_d0:3;
        u32 rsvd_19:5;
        u32 cmdphy_tdie_d0:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg18_t;

#define CMDPHY_CTRL_REG19                        0x000000d4
#define   CMDPHY_PU_d4_MASK                      0x07000000
#define   CMDPHY_PU_d4_SHIFT                             24
#define   CMDPHY_PD_d4_MASK                      0x00070000
#define   CMDPHY_PD_d4_SHIFT                             16
#define   CMDPHY_DQ_SLR_d4_MASK                  0x00000700
#define   CMDPHY_DQ_SLR_d4_SHIFT                          8
#define   CMDPHY_DQ_MS_d4_MASK                   0x00000007
#define   CMDPHY_DQ_MS_d4_SHIFT                           0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dq_ms_d4:3;
        u32 rsvd_3:5;
        u32 cmdphy_dq_slr_d4:3;
        u32 rsvd_11:5;
        u32 cmdphy_pd_d4:3;
        u32 rsvd_19:5;
        u32 cmdphy_pu_d4:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg19_t;

#define CMDPHY_CTRL_REG20                        0x000000d8
#define   CMDPHY_DSTR3_d8_MASK                   0x07000000
#define   CMDPHY_DSTR3_d8_SHIFT                          24
#define   CMDPHY_DSTR2_d8_MASK                   0x00070000
#define   CMDPHY_DSTR2_d8_SHIFT                          16
#define   CMDPHY_DSTR1_d8_MASK                   0x00000700
#define   CMDPHY_DSTR1_d8_SHIFT                           8
#define   CMDPHY_DSTR0_d8_MASK                   0x00000007
#define   CMDPHY_DSTR0_d8_SHIFT                           0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_dstr0_d8:3;
        u32 rsvd_3:5;
        u32 cmdphy_dstr1_d8:3;
        u32 rsvd_11:5;
        u32 cmdphy_dstr2_d8:3;
        u32 rsvd_19:5;
        u32 cmdphy_dstr3_d8:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg20_t;

#define CMDPHY_CTRL_REG21                        0x000000dc
#define   CMDPHY_ODT_SEL3_dc_MASK                0x07000000
#define   CMDPHY_ODT_SEL3_dc_SHIFT                       24
#define   CMDPHY_ODT_SEL2_dc_MASK                0x00070000
#define   CMDPHY_ODT_SEL2_dc_SHIFT                       16
#define   CMDPHY_ODT_SEL1_dc_MASK                0x00000700
#define   CMDPHY_ODT_SEL1_dc_SHIFT                        8
#define   CMDPHY_ODT_SEL0_dc_MASK                0x00000007
#define   CMDPHY_ODT_SEL0_dc_SHIFT                        0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_odt_sel0_dc:3;
        u32 rsvd_3:5;
        u32 cmdphy_odt_sel1_dc:3;
        u32 rsvd_11:5;
        u32 cmdphy_odt_sel2_dc:3;
        u32 rsvd_19:5;
        u32 cmdphy_odt_sel3_dc:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg21_t;

#define CMDPHY_CTRL_REG22                        0x000000e0
#define   CMDPHY_CLK2X_DQD_DLY7_e0_MASK          0x07000000
#define   CMDPHY_CLK2X_DQD_DLY7_e0_SHIFT                 24
#define   CMDPHY_CLK2X_DQD_DLY6_e0_MASK          0x00070000
#define   CMDPHY_CLK2X_DQD_DLY6_e0_SHIFT                 16
#define   CMDPHY_CLK2X_DQD_DLY5_e0_MASK          0x00000700
#define   CMDPHY_CLK2X_DQD_DLY5_e0_SHIFT                  8
#define   CMDPHY_CLK2X_DQD_DLY4_e0_MASK          0x00000007
#define   CMDPHY_CLK2X_DQD_DLY4_e0_SHIFT                  0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_dqd_dly4_e0:3;
        u32 rsvd_3:5;
        u32 cmdphy_clk2x_dqd_dly5_e0:3;
        u32 rsvd_11:5;
        u32 cmdphy_clk2x_dqd_dly6_e0:3;
        u32 rsvd_19:5;
        u32 cmdphy_clk2x_dqd_dly7_e0:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg22_t;

#define CMDPHY_CTRL_REG23                        0x000000e4
#define   CMDPHY_CLK2X_DQD_DLY3_e4_MASK          0x07000000
#define   CMDPHY_CLK2X_DQD_DLY3_e4_SHIFT                 24
#define   CMDPHY_CLK2X_DQD_DLY2_e4_MASK          0x00070000
#define   CMDPHY_CLK2X_DQD_DLY2_e4_SHIFT                 16
#define   CMDPHY_CLK2X_DQD_DLY1_e4_MASK          0x00000700
#define   CMDPHY_CLK2X_DQD_DLY1_e4_SHIFT                  8
#define   CMDPHY_CLK2X_DQD_DLY0_e4_MASK          0x00000007
#define   CMDPHY_CLK2X_DQD_DLY0_e4_SHIFT                  0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_dqd_dly0_e4:3;
        u32 rsvd_3:5;
        u32 cmdphy_clk2x_dqd_dly1_e4:3;
        u32 rsvd_11:5;
        u32 cmdphy_clk2x_dqd_dly2_e4:3;
        u32 rsvd_19:5;
        u32 cmdphy_clk2x_dqd_dly3_e4:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg23_t;

#define CMDPHY_CTRL_REG24                        0x000000e8
#define   CMDPHY_CLK2X_DQC_DLY7_e8_MASK          0x07000000
#define   CMDPHY_CLK2X_DQC_DLY7_e8_SHIFT                 24
#define   CMDPHY_CLK2X_DQC_DLY6_e8_MASK          0x00070000
#define   CMDPHY_CLK2X_DQC_DLY6_e8_SHIFT                 16
#define   CMDPHY_CLK2X_DQC_DLY5_e8_MASK          0x00000700
#define   CMDPHY_CLK2X_DQC_DLY5_e8_SHIFT                  8
#define   CMDPHY_CLK2X_DQC_DLY4_e8_MASK          0x00000007
#define   CMDPHY_CLK2X_DQC_DLY4_e8_SHIFT                  0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_dqc_dly4_e8:3;
        u32 rsvd_3:5;
        u32 cmdphy_clk2x_dqc_dly5_e8:3;
        u32 rsvd_11:5;
        u32 cmdphy_clk2x_dqc_dly6_e8:3;
        u32 rsvd_19:5;
        u32 cmdphy_clk2x_dqc_dly7_e8:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg24_t;

#define CMDPHY_CTRL_REG25                        0x000000ec
#define   CMDPHY_CLK2X_DQC_DLY3_ec_MASK          0x07000000
#define   CMDPHY_CLK2X_DQC_DLY3_ec_SHIFT                 24
#define   CMDPHY_CLK2X_DQC_DLY2_ec_MASK          0x00070000
#define   CMDPHY_CLK2X_DQC_DLY2_ec_SHIFT                 16
#define   CMDPHY_CLK2X_DQC_DLY1_ec_MASK          0x00000700
#define   CMDPHY_CLK2X_DQC_DLY1_ec_SHIFT                  8
#define   CMDPHY_CLK2X_DQC_DLY0_ec_MASK          0x00000007
#define   CMDPHY_CLK2X_DQC_DLY0_ec_SHIFT                  0

typedef union {
    u32 all;
    struct {
        u32 cmdphy_clk2x_dqc_dly0_ec:3;
        u32 rsvd_3:5;
        u32 cmdphy_clk2x_dqc_dly1_ec:3;
        u32 rsvd_11:5;
        u32 cmdphy_clk2x_dqc_dly2_ec:3;
        u32 rsvd_19:5;
        u32 cmdphy_clk2x_dqc_dly3_ec:3;
        u32 rsvd_27:5;
    } b;
} cmdphy_ctrl_reg25_t;

#define CMDPHY_CTRL_REG26                        0x000000f0
#define   CMDPHY_WP_RCVTYPE_MASK                 0x00004000
#define   CMDPHY_WP_RCVTYPE_SHIFT                        14
#define   CMDPHY_WP_PU_MASK                      0x00002000
#define   CMDPHY_WP_PU_SHIFT                             13
#define   CMDPHY_WP_PD_MASK                      0x00001000
#define   CMDPHY_WP_PD_SHIFT                             12
#define   CMDPHY_WP_ZQTRIM_MASK                  0x00000c00
#define   CMDPHY_WP_ZQTRIM_SHIFT                         10
#define   CMDPHY_WP_MS_MASK                      0x00000200
#define   CMDPHY_WP_MS_SHIFT                              9
#define   CMDPHY_WP_SLR_MASK                     0x00000100
#define   CMDPHY_WP_SLR_SHIFT                             8
#define   CMDPHY_WP_DSTR_MASK                    0x000000f0
#define   CMDPHY_WP_DSTR_SHIFT                            4
#define   CMDPHY_WP_ODT_SEL_MASK                 0x0000000e
#define   CMDPHY_WP_ODT_SEL_SHIFT                         1
#define   CMDPHY_WP_ODT_EN_MASK                  0x00000001
#define   CMDPHY_WP_ODT_EN_SHIFT                          0
typedef union {
    u32 all;
    struct {
        u32 cmdphy_wp_odt_en:1;
        u32 cmdphy_wp_odt_sel:3;
        u32 cmdphy_wp_dstr:4;
        u32 cmdphy_wp_slr:1;
        u32 cmdphy_wp_ms:1;
        u32 cmdphy_wp_zqtrim:2;
        u32 cmdphy_wp_pd:1;
        u32 cmdphy_wp_pu:1;
        u32 cmdphy_wp_rcvtype:1;
        u32 rsvd_15:17;
    } b;
} cmdphy_ctrl_reg26_t;


#ifndef REG_GFLD
# define REG_GFLD(val, FLD) (((u32)(val) &  FLD ## _MASK) >> FLD ## _SHIFT)
# define REG_SFLD(val, FLD) (((u32)(val) << FLD ## _SHIFT) & FLD ## _MASK)
# define REG_RMW(o, n, FLD) ((((u32)(o) & ~ FLD ## _MASK)) | (((u32)(n) << FLD ## _SHIFT)))
#endif

typedef struct {
    /* 0x0000 */ nphy_ctrl_reg0_t nphy_ctrl_reg0;
    /* 0x0004 */ nphy_ctrl_reg1_t nphy_ctrl_reg1;
    /* 0x0008 */ dtphy_ctrl_reg0_t dtphy_ctrl_reg0;
    /* 0x000c */ dtphy_ctrl_reg1_t dtphy_ctrl_reg1;
    /* 0x0010 */ dtphy_ctrl_reg2_t dtphy_ctrl_reg2;
    /* 0x0014 */ dtphy_ctrl_reg3_t dtphy_ctrl_reg3;
    /* 0x0018 */ dtphy_ctrl_reg4_t dtphy_ctrl_reg4;
    /* 0x001c */ dtphy_ctrl_reg5_t dtphy_ctrl_reg5;
    /* 0x0020 */ dtphy_ctrl_reg6_t dtphy_ctrl_reg6;
    /* 0x0024 */ dtphy_ctrl_reg7_t dtphy_ctrl_reg7;
    /* 0x0028 */ dtphy_ctrl_reg8_t dtphy_ctrl_reg8;
    /* 0x002c */ dtphy_ctrl_reg9_t dtphy_ctrl_reg9;
    /* 0x0030 */ dtphy_ctrl_reg10_t dtphy_ctrl_reg10;
    /* 0x0034 */ dtphy_ctrl_reg11_t dtphy_ctrl_reg11;
    /* 0x0038 */ dtphy_ctrl_reg12_t dtphy_ctrl_reg12;
    /* 0x003c */ dtphy_ctrl_reg13_t dtphy_ctrl_reg13;
    /* 0x0040 */ dtphy_ctrl_reg14_t dtphy_ctrl_reg14;
    /* 0x0044 */ dtphy_ctrl_reg15_t dtphy_ctrl_reg15;
    /* 0x0048 */ dtphy_ctrl_reg16_t dtphy_ctrl_reg16;
    /* 0x004c */ dtphy_ctrl_reg17_t dtphy_ctrl_reg17;
    /* 0x0050 */ dtphy_dll_cfg_ptr_t dtphy_dll_cfg_ptr;
    /* 0x0054 */ dtphy_dll_phase_t dtphy_dll_phase;
    /* 0x0058 */ dtphy_dll_dq_dly_t dtphy_dll_dq_dly;
    /* 0x005c */ u32 rsvd_5c;
    /* 0x0060 */ nd_phy_calib_reg0_t nd_phy_calib_reg0;
    /* 0x0064 */ u32 rsvd_64 [7];
    /* 0x0080 */ cmdphy_wp_ctrl_reg_t cmdphy_wp_ctrl_reg;
    /* 0x0084 */ u32 rsvd_84;
    /* 0x0088 */ cmdphy_ctrl_reg0_t cmdphy_ctrl_reg0;
    /* 0x008c */ cmdphy_ctrl_reg1_t cmdphy_ctrl_reg1;
    /* 0x0090 */ cmdphy_ctrl_reg2_t cmdphy_ctrl_reg2;
    /* 0x0094 */ cmdphy_ctrl_reg3_t cmdphy_ctrl_reg3;
    /* 0x0098 */ cmdphy_ctrl_reg4_t cmdphy_ctrl_reg4;
    /* 0x009c */ cmdphy_ctrl_reg5_t cmdphy_ctrl_reg5;
    /* 0x00a0 */ cmdphy_ctrl_reg6_t cmdphy_ctrl_reg6;
    /* 0x00a4 */ cmdphy_ctrl_reg7_t cmdphy_ctrl_reg7;
    /* 0x00a8 */ cmdphy_ctrl_reg8_t cmdphy_ctrl_reg8;
    /* 0x00ac */ cmdphy_ctrl_reg9_t cmdphy_ctrl_reg9;
    /* 0x00b0 */ cmdphy_ctrl_reg10_t cmdphy_ctrl_reg10;
    /* 0x00b4 */ cmdphy_ctrl_reg11_t cmdphy_ctrl_reg11;
    /* 0x00b8 */ cmdphy_ctrl_reg12_t cmdphy_ctrl_reg12;
    /* 0x00bc */ cmdphy_ctrl_reg13_t cmdphy_ctrl_reg13;
    /* 0x00c0 */ cmdphy_ctrl_reg14_t cmdphy_ctrl_reg14;
    /* 0x00c4 */ cmdphy_ctrl_reg15_t cmdphy_ctrl_reg15;
    /* 0x00c8 */ cmdphy_ctrl_reg16_t cmdphy_ctrl_reg16;
    /* 0x00cc */ cmdphy_ctrl_reg17_t cmdphy_ctrl_reg17;
    /* 0x00d0 */ cmdphy_ctrl_reg18_t cmdphy_ctrl_reg18;
    /* 0x00d4 */ cmdphy_ctrl_reg19_t cmdphy_ctrl_reg19;
    /* 0x00d8 */ cmdphy_ctrl_reg20_t cmdphy_ctrl_reg20;
    /* 0x00dc */ cmdphy_ctrl_reg21_t cmdphy_ctrl_reg21;
    /* 0x00e0 */ cmdphy_ctrl_reg22_t cmdphy_ctrl_reg22;
    /* 0x00e4 */ cmdphy_ctrl_reg23_t cmdphy_ctrl_reg23;
    /* 0x00e8 */ cmdphy_ctrl_reg24_t cmdphy_ctrl_reg24;
    /* 0x00ec */ cmdphy_ctrl_reg25_t cmdphy_ctrl_reg25;
    /* 0x00f0 */ cmdphy_ctrl_reg26_t cmdphy_ctrl_reg26;
} ndphy_regs_t;


#endif /* rev 1004 */