#!/bin/bash
if [[ $fw == *"Lenovo_case"* ]]; then
	echo "Lenovo_case"
	arg="$arg -DLenovo_case=1"
fi

if [[ $fw == *"Smart_Modular_case"* ]]; then
	echo "Smart_Modular_case"
	arg="$arg -DSmart_Modular_case=1"
fi

if [[ $fw == *"_WUNC_"* ]]; then
	echo "_WUNC_"
	arg="$arg -D_WUNC_=1"
fi

if [[ $fw == *"Xfusion_case"* ]]; then
	echo "Xfusion_case"
	arg="$arg -DXfusion_case=1"
fi

if [[ $fw == *"iEi_case"* ]]; then
	echo "iEi_case"
	arg="$arg -DiEi_case=1"
fi

if [[ $fw == *"Add_smart"* ]]; then
	echo "Add_smart"
	arg="$arg -DAdd_smart=1"
fi

if [[ $fw == *"Tencent_case"* ]]; then
	echo "Tencent_case"
	arg="$arg -DTencent_case=1"
fi

if [[ $fw == *"Synology_case"* ]]; then
	echo "Synology_case"
	arg="$arg -DSynology_case=1"
fi
if [[ $fw == *"Baidu_case"* ]]; then
	echo "Baidu_case"
	arg="$arg -DBaidu_case=1"
fi

if [[ $fw == *"RD_VERIFY"* ]]; then
	echo "RD_VERIFY"
	arg="$arg -DRD_VERIFY=1"
fi

if [[ $fw == *"DST"* ]]; then
	echo "Device Self-Test"
	arg="$arg -DDST=1"
fi

if [[ $fw == *"4k"* ]]; then
	echo "4K sector"
	arg="$arg -DSEC_4K=1"
fi

if [[ $fw == *"full"* ]]; then
	echo "full"
	if [[ $fw == *"ramdisk"* ]]; then
		arg="$arg -DRAMDISK_FULL=1"
	fi
fi

if [[ $fw == *"8kdu"* ]]; then
	echo "8K DU"
	arg="$arg -DUSE_8K_DU=1"
fi

if [[ $fw == *"512b"* ]]; then
	echo "512b sector"
	arg="$arg -DUSE_512B_HOST_SECTOR_SIZE=1"
fi

if [[ $fw == *"aes"* ]]; then
	echo "AES"
	arg="$arg -DUSE_CRYPTO_HW=1"
fi

if [[ $fw == *"sm4"* ]]; then
	echo "sm4"
	arg="$arg -DUSE_CRYPTO_HW=1 -DUSE_SM4_ALGO=1"
fi

if [[ $fw == *"ddr_half"* ]]; then
	echo "ddr_half"
	arg="$arg -DDDR_TEST=1 -DDDR=1 -DDDR_HALF=1"
elif [[ $fw == *"ddr"* ]]; then
	echo "ddr"
	#arg="$arg -DDDR_TEST=1 -DDDR=1"
fi

if [[ $fw == *"hcrc"* ]]; then
	echo "hcrc"
	arg="$arg -DDISABLE_HS_CRC_SUPPORT=0"
else
	arg="$arg -DDISABLE_HS_CRC_SUPPORT=1"
fi

if [[ $fw == *"semi"* ]]; then
	echo "semi_write"
	arg="$arg -DSEMI_WRITE_ENABLE=1"
fi

if [[ $fw == *"pi8"* ]]; then
	echo "8 bytes PI"
	arg="$arg -DHMETA_SIZE=8 -DPI_SUPPORT=1"
fi

if [[ $fw == *"mdot2"* ]]; then
	echo "mdoat2 support"
	arg="$arg -DMDOT2_SUPPORT=1"
fi

if [[ $fw == *"plp_debug"* ]]; then
	echo "plp debug"
	arg="$arg -DPLP_DEBUG=1"
fi

if [[ $fw == *"hmeta8"* ]]; then
	echo "8 bytes hmeta"
	arg="$arg -DHMETA_SIZE=8"
fi

if [[ $fw == *"pi16"* ]]; then
	echo "16 bytes PI"
	arg="$arg -DHMETA_SIZE=16 -DPI_SUPPORT=1"
fi

if [[ $fw == *"hmeta16"* ]]; then
	echo "16 bytes hmeta"
	arg="$arg -DHMETA_SIZE=16"
fi

if [[ $fw == *"pecc"* ]]; then
	echo "parallel ecc"
	arg="$arg -DENABLE_PARALLEL_ECC=1"
fi

if [[ $fw == *"iecc"* ]]; then
	echo "inline ecc"
	arg="$arg -DENABLE_INLINE_ECC=1"
fi

if [[ $fw == *"secc"* ]]; then
	echo "sram ecc"
	arg="$arg -DENABLE_SRAM_ECC=1"
fi

if [[ $fw == *"merge_wa"* ]]; then
	echo "merge_wa"
	arg="$arg -DMERGE_WA=1"
fi

if [[ $fw == *"l2c"* ]]; then
	echo "l2cache"
	arg="$arg -DENABLE_L2CACHE=1"
fi

if [[ $fw == *"atomic"* ]]; then
	echo "atomic"
	arg="$arg -DATOMIC=1"
fi

if [[ $fw == *"nm"* ]]; then
	echo "namespace manage"
	arg="$arg -DNS_MANAGE=1"
fi

if [[ $fw == *"tsb"* ]]; then
	echo "toshiba using"
	arg="$arg -DUSE_TSB_NAND=1"
fi

if [[ $fw == *"mu"* ]]; then
	echo "micron using"
	arg="$arg -DUSE_MU_NAND=1"
fi

if [[ $fw == *"b27b"* ]]; then
	echo "b27b using"
	arg="$arg -DMU_B27B=1 -DUSE_MU_NAND=1"
fi

if [[ $fw == *"3dv4"* ]]; then
	echo "hynix 3dv4"
	arg="$arg -DUSE_HYNX_NAND=1 -DUSE_8K_PAGE=1"
fi

if [[ $fw == *"3dv5"* ]]; then
	echo "hynix 3dv5"
	arg="$arg -DUSE_HYNX_NAND=1"
fi

if [[ $fw == *"qlc"* ]]; then
	echo "QLC"
	arg="$arg -DQLC_SUPPORT=1"
fi

if [[ $fw == *"lpddr4"* ]]; then
	echo "LPDDR4"
	arg="$arg -DLPDDR4=1 -DDDR_TEST=1 -DDDR=1"
elif [[ $fw == *"ddr4"* ]]; then
	echo "DDR4"
	arg="$arg -DDDR4=1 -DDDR_TEST=1 -DDDR=1"
fi

if [[ $fw == *"512m"* ]]; then
	echo "size 512m"
	arg="$arg -DDDR_SIZE_RAINIER=0x20000000"
fi

if [[ $fw == *"1g"* ]]; then
	echo "size 1g"
	arg="$arg -DDDR_SIZE_RAINIER=0x40000000"
fi

if [[ $fw == *"2g"* ]]; then
	echo "size 2g"
	arg="$arg -DDDR_SIZE_RAINIER=0x80000000"
fi

if [[ $fw == *"4g"* ]]; then
	echo "size 4g"
	arg="$arg -DDDR_SIZE_RAINIER=0x100000000"
fi

if [[ $fw == *"8g"* ]]; then
	echo "size 8g"
	arg="$arg -DDDR_SIZE_RAINIER=0x200000000"
fi

if [[ $fw == *"raid"* ]]; then
	echo "raid"
	arg="$arg -DRAID_SUPPORT=1"
	arg="$arg -DXOR_CMPL_BY_PDONE=1"
fi

if [[ $fw == *"cust"* ]]; then
	echo "customer"
	arg="$arg -DCUSTOMER=1"
fi

if [[ $fw == *"pxlc"* ]]; then
	echo "pure XLC"
	arg="$arg -DPURE_XLC=1"
fi

if [[ $fw == *"disable_wa6654"* ]]; then
    echo "DISABLE_WA_6654"
    arg="$arg -DWA_6654=0"
else
    echo "ENABLE_WA_6654"
    arg="$arg -DWA_6654=1"
fi

if [[ $fw == *"pslc"* ]]; then
	echo "pure SLC"
	arg="$arg -DPURE_SLC=1"
fi

if [[ $fw == *"plp"* ]]; then
	echo "internal plp"
	arg="$arg -DPLP_SUPPORT=1"
fi

if [[ $fw == *"savecdump"* ]]; then
	echo "write box"
	arg="$arg -DSAVE_CDUMP=1"
fi

if [[ $fw == *"TCG"* ]]; then
	echo "TCG"
	arg="$arg -DTCG_SUPPORT=1"
else
	echo "non-TCG"
	arg="$arg -DTCG_SUPPORT=0"
fi

