#!/bin/bash
echo "======================================================="
echo "\"loader_ver\" start"
if [ $board_cfg == "fpga" ]; then
	loader="fpga_rainier_loader_a0.fw"
	Sloader="fpga_rainier_loader_a0_security.fw"
else
	if [ $loader_uart == 1 ]; then
		loader="LJ1_LDR_uartlog.fw"
    #loader="rainier_loader_a0_uartlog.fw"
	else
    loader="LJ1_LDR.fw" 
    #loader="rainier_loader_a0.fw"
	fi
	Sloader="rainier_loader_a0_security.fw"
fi

echo "loader: $loader"
echo "Sloader: $Sloader"
echo "======================================================="